#ifndef LUASTEAM_AUTO_HPP
#define LUASTEAM_AUTO_HPP

#include "../common.hpp"
#include <vector>

namespace luasteam {

void add_enums_auto(lua_State *L);
void add_consts_auto(lua_State *L);
void init_structs_auto(lua_State *L);
void shutdown_structs_auto(lua_State *L);
void add_structs_auto(lua_State *L);
FriendGameInfo_t check_FriendGameInfo_t(lua_State *L, int index);
void push_FriendGameInfo_t(lua_State *L, FriendGameInfo_t val);
InputAnalogActionData_t check_InputAnalogActionData_t(lua_State *L, int index);
void push_InputAnalogActionData_t(lua_State *L, InputAnalogActionData_t val);
InputDigitalActionData_t check_InputDigitalActionData_t(lua_State *L, int index);
void push_InputDigitalActionData_t(lua_State *L, InputDigitalActionData_t val);
InputMotionData_t check_InputMotionData_t(lua_State *L, int index);
void push_InputMotionData_t(lua_State *L, InputMotionData_t val);
LeaderboardEntry_t check_LeaderboardEntry_t(lua_State *L, int index);
void push_LeaderboardEntry_t(lua_State *L, LeaderboardEntry_t val);
MatchMakingKeyValuePair_t check_MatchMakingKeyValuePair_t(lua_State *L, int index);
void push_MatchMakingKeyValuePair_t(lua_State *L, MatchMakingKeyValuePair_t val);
P2PSessionState_t check_P2PSessionState_t(lua_State *L, int index);
void push_P2PSessionState_t(lua_State *L, P2PSessionState_t val);
RemotePlayInputKey_t check_RemotePlayInputKey_t(lua_State *L, int index);
void push_RemotePlayInputKey_t(lua_State *L, RemotePlayInputKey_t val);
RemotePlayInputMouseMotion_t check_RemotePlayInputMouseMotion_t(lua_State *L, int index);
void push_RemotePlayInputMouseMotion_t(lua_State *L, RemotePlayInputMouseMotion_t val);
RemotePlayInputMouseWheel_t check_RemotePlayInputMouseWheel_t(lua_State *L, int index);
void push_RemotePlayInputMouseWheel_t(lua_State *L, RemotePlayInputMouseWheel_t val);
RemotePlayInput_t check_RemotePlayInput_t(lua_State *L, int index);
void push_RemotePlayInput_t(lua_State *L, RemotePlayInput_t val);
SteamIPAddress_t check_SteamIPAddress_t(lua_State *L, int index);
void push_SteamIPAddress_t(lua_State *L, SteamIPAddress_t val);
SteamInputActionEvent_t check_SteamInputActionEvent_t(lua_State *L, int index);
void push_SteamInputActionEvent_t(lua_State *L, SteamInputActionEvent_t val);
SteamItemDetails_t check_SteamItemDetails_t(lua_State *L, int index);
void push_SteamItemDetails_t(lua_State *L, SteamItemDetails_t val);
SteamNetConnectionInfo_t check_SteamNetConnectionInfo_t(lua_State *L, int index);
void push_SteamNetConnectionInfo_t(lua_State *L, SteamNetConnectionInfo_t val);
SteamNetConnectionRealTimeLaneStatus_t check_SteamNetConnectionRealTimeLaneStatus_t(lua_State *L, int index);
void push_SteamNetConnectionRealTimeLaneStatus_t(lua_State *L, SteamNetConnectionRealTimeLaneStatus_t val);
SteamNetConnectionRealTimeStatus_t check_SteamNetConnectionRealTimeStatus_t(lua_State *L, int index);
void push_SteamNetConnectionRealTimeStatus_t(lua_State *L, SteamNetConnectionRealTimeStatus_t val);
SteamNetworkPingLocation_t check_SteamNetworkPingLocation_t(lua_State *L, int index);
void push_SteamNetworkPingLocation_t(lua_State *L, SteamNetworkPingLocation_t val);
SteamNetworkingConfigValue_t check_SteamNetworkingConfigValue_t(lua_State *L, int index);
void push_SteamNetworkingConfigValue_t(lua_State *L, SteamNetworkingConfigValue_t val);
SteamNetworkingIPAddr check_SteamNetworkingIPAddr(lua_State *L, int index);
void push_SteamNetworkingIPAddr(lua_State *L, SteamNetworkingIPAddr val);
SteamNetworkingIdentity check_SteamNetworkingIdentity(lua_State *L, int index);
void push_SteamNetworkingIdentity(lua_State *L, SteamNetworkingIdentity val);
SteamParamStringArray_t check_SteamParamStringArray_t(lua_State *L, int index);
void push_SteamParamStringArray_t(lua_State *L, SteamParamStringArray_t val);
SteamPartyBeaconLocation_t check_SteamPartyBeaconLocation_t(lua_State *L, int index);
void push_SteamPartyBeaconLocation_t(lua_State *L, SteamPartyBeaconLocation_t val);
SteamUGCDetails_t check_SteamUGCDetails_t(lua_State *L, int index);
void push_SteamUGCDetails_t(lua_State *L, SteamUGCDetails_t val);
gameserveritem_t check_gameserveritem_t(lua_State *L, int index);
void push_gameserveritem_t(lua_State *L, gameserveritem_t val);
servernetadr_t check_servernetadr_t(lua_State *L, int index);
void push_servernetadr_t(lua_State *L, servernetadr_t val);
FriendGameInfo_t *check_FriendGameInfo_t_ptr(lua_State *L, int index);
InputAnalogActionData_t *check_InputAnalogActionData_t_ptr(lua_State *L, int index);
InputDigitalActionData_t *check_InputDigitalActionData_t_ptr(lua_State *L, int index);
InputMotionData_t *check_InputMotionData_t_ptr(lua_State *L, int index);
LeaderboardEntry_t *check_LeaderboardEntry_t_ptr(lua_State *L, int index);
MatchMakingKeyValuePair_t *check_MatchMakingKeyValuePair_t_ptr(lua_State *L, int index);
P2PSessionState_t *check_P2PSessionState_t_ptr(lua_State *L, int index);
RemotePlayInputKey_t *check_RemotePlayInputKey_t_ptr(lua_State *L, int index);
RemotePlayInputMouseMotion_t *check_RemotePlayInputMouseMotion_t_ptr(lua_State *L, int index);
RemotePlayInputMouseWheel_t *check_RemotePlayInputMouseWheel_t_ptr(lua_State *L, int index);
RemotePlayInput_t *check_RemotePlayInput_t_ptr(lua_State *L, int index);
SteamIPAddress_t *check_SteamIPAddress_t_ptr(lua_State *L, int index);
SteamInputActionEvent_t *check_SteamInputActionEvent_t_ptr(lua_State *L, int index);
SteamItemDetails_t *check_SteamItemDetails_t_ptr(lua_State *L, int index);
SteamNetConnectionInfo_t *check_SteamNetConnectionInfo_t_ptr(lua_State *L, int index);
SteamNetConnectionRealTimeLaneStatus_t *check_SteamNetConnectionRealTimeLaneStatus_t_ptr(lua_State *L, int index);
SteamNetConnectionRealTimeStatus_t *check_SteamNetConnectionRealTimeStatus_t_ptr(lua_State *L, int index);
SteamNetworkPingLocation_t *check_SteamNetworkPingLocation_t_ptr(lua_State *L, int index);
SteamNetworkingConfigValue_t *check_SteamNetworkingConfigValue_t_ptr(lua_State *L, int index);
SteamNetworkingIPAddr *check_SteamNetworkingIPAddr_ptr(lua_State *L, int index);
SteamNetworkingIdentity *check_SteamNetworkingIdentity_ptr(lua_State *L, int index);
SteamParamStringArray_t *check_SteamParamStringArray_t_ptr(lua_State *L, int index);
SteamPartyBeaconLocation_t *check_SteamPartyBeaconLocation_t_ptr(lua_State *L, int index);
SteamUGCDetails_t *check_SteamUGCDetails_t_ptr(lua_State *L, int index);
gameserveritem_t *check_gameserveritem_t_ptr(lua_State *L, int index);
servernetadr_t *check_servernetadr_t_ptr(lua_State *L, int index);
void register_User_auto(lua_State *L);
void add_User_auto(lua_State *L);
void init_User_auto(lua_State *L);
void shutdown_User_auto(lua_State *L);
extern int User_ref;
void register_Friends_auto(lua_State *L);
void add_Friends_auto(lua_State *L);
void init_Friends_auto(lua_State *L);
void shutdown_Friends_auto(lua_State *L);
extern int Friends_ref;
void register_Utils_auto(lua_State *L);
void add_Utils_auto(lua_State *L);
void init_Utils_auto(lua_State *L);
void shutdown_Utils_auto(lua_State *L);
extern int Utils_ref;
void register_Matchmaking_auto(lua_State *L);
void add_Matchmaking_auto(lua_State *L);
void init_Matchmaking_auto(lua_State *L);
void shutdown_Matchmaking_auto(lua_State *L);
extern int Matchmaking_ref;
void register_MatchmakingServers_auto(lua_State *L);
void add_MatchmakingServers_auto(lua_State *L);
void init_MatchmakingServers_auto(lua_State *L);
void shutdown_MatchmakingServers_auto(lua_State *L);
extern int MatchmakingServers_ref;
void register_Parties_auto(lua_State *L);
void add_Parties_auto(lua_State *L);
void init_Parties_auto(lua_State *L);
void shutdown_Parties_auto(lua_State *L);
extern int Parties_ref;
void register_RemoteStorage_auto(lua_State *L);
void add_RemoteStorage_auto(lua_State *L);
void init_RemoteStorage_auto(lua_State *L);
void shutdown_RemoteStorage_auto(lua_State *L);
extern int RemoteStorage_ref;
void register_UserStats_auto(lua_State *L);
void add_UserStats_auto(lua_State *L);
void init_UserStats_auto(lua_State *L);
void shutdown_UserStats_auto(lua_State *L);
extern int UserStats_ref;
void register_Apps_auto(lua_State *L);
void add_Apps_auto(lua_State *L);
void init_Apps_auto(lua_State *L);
void shutdown_Apps_auto(lua_State *L);
extern int Apps_ref;
void register_Screenshots_auto(lua_State *L);
void add_Screenshots_auto(lua_State *L);
void init_Screenshots_auto(lua_State *L);
void shutdown_Screenshots_auto(lua_State *L);
extern int Screenshots_ref;
void register_Music_auto(lua_State *L);
void add_Music_auto(lua_State *L);
void init_Music_auto(lua_State *L);
void shutdown_Music_auto(lua_State *L);
extern int Music_ref;
void register_Input_auto(lua_State *L);
void add_Input_auto(lua_State *L);
void init_Input_auto(lua_State *L);
void shutdown_Input_auto(lua_State *L);
extern int Input_ref;
void register_Controller_auto(lua_State *L);
void add_Controller_auto(lua_State *L);
void init_Controller_auto(lua_State *L);
void shutdown_Controller_auto(lua_State *L);
extern int Controller_ref;
void register_UGC_auto(lua_State *L);
void add_UGC_auto(lua_State *L);
void init_UGC_auto(lua_State *L);
void shutdown_UGC_auto(lua_State *L);
extern int UGC_ref;
void register_HTMLSurface_auto(lua_State *L);
void add_HTMLSurface_auto(lua_State *L);
void init_HTMLSurface_auto(lua_State *L);
void shutdown_HTMLSurface_auto(lua_State *L);
extern int HTMLSurface_ref;
void register_Inventory_auto(lua_State *L);
void add_Inventory_auto(lua_State *L);
void init_Inventory_auto(lua_State *L);
void shutdown_Inventory_auto(lua_State *L);
extern int Inventory_ref;
void register_Timeline_auto(lua_State *L);
void add_Timeline_auto(lua_State *L);
void init_Timeline_auto(lua_State *L);
void shutdown_Timeline_auto(lua_State *L);
extern int Timeline_ref;
void register_Video_auto(lua_State *L);
void add_Video_auto(lua_State *L);
void init_Video_auto(lua_State *L);
void shutdown_Video_auto(lua_State *L);
extern int Video_ref;
void register_ParentalSettings_auto(lua_State *L);
void add_ParentalSettings_auto(lua_State *L);
void init_ParentalSettings_auto(lua_State *L);
void shutdown_ParentalSettings_auto(lua_State *L);
extern int ParentalSettings_ref;
void register_RemotePlay_auto(lua_State *L);
void add_RemotePlay_auto(lua_State *L);
void init_RemotePlay_auto(lua_State *L);
void shutdown_RemotePlay_auto(lua_State *L);
extern int RemotePlay_ref;
void register_GameServer_auto(lua_State *L);
void add_GameServer_auto(lua_State *L);
void init_GameServer_auto(lua_State *L);
void shutdown_GameServer_auto(lua_State *L);
extern int GameServer_ref;
void register_GameServerStats_auto(lua_State *L);
void add_GameServerStats_auto(lua_State *L);
void init_GameServerStats_auto(lua_State *L);
void shutdown_GameServerStats_auto(lua_State *L);
extern int GameServerStats_ref;

} // namespace luasteam

#endif // LUASTEAM_AUTO_HPP
