#ifndef LUASTEAM_AUTO_HPP
#define LUASTEAM_AUTO_HPP

#include "../common.hpp"
#include <vector>

namespace luasteam {

void add_enums_auto(lua_State *L);
void add_consts_auto(lua_State *L);
void init_structs_auto(lua_State *L);
void shutdown_structs_auto(lua_State *L);
void add_structs_auto(lua_State *L);
void init_callback_interfaces_auto(lua_State *L);
void shutdown_callback_interfaces_auto(lua_State *L);
void add_callback_interfaces_auto(lua_State *L);
ISteamMatchmakingPingResponse *check_ISteamMatchmakingPingResponse(lua_State *L, int idx);
ISteamMatchmakingPlayersResponse *check_ISteamMatchmakingPlayersResponse(lua_State *L, int idx);
ISteamMatchmakingRulesResponse *check_ISteamMatchmakingRulesResponse(lua_State *L, int idx);
ISteamMatchmakingServerListResponse *check_ISteamMatchmakingServerListResponse(lua_State *L, int idx);
ActiveBeaconsUpdated_t check_ActiveBeaconsUpdated_t(lua_State *L, int index);
void push_ActiveBeaconsUpdated_t(lua_State *L, ActiveBeaconsUpdated_t val);
AddAppDependencyResult_t check_AddAppDependencyResult_t(lua_State *L, int index);
void push_AddAppDependencyResult_t(lua_State *L, AddAppDependencyResult_t val);
AddUGCDependencyResult_t check_AddUGCDependencyResult_t(lua_State *L, int index);
void push_AddUGCDependencyResult_t(lua_State *L, AddUGCDependencyResult_t val);
AppProofOfPurchaseKeyResponse_t check_AppProofOfPurchaseKeyResponse_t(lua_State *L, int index);
void push_AppProofOfPurchaseKeyResponse_t(lua_State *L, AppProofOfPurchaseKeyResponse_t val);
AppResumingFromSuspend_t check_AppResumingFromSuspend_t(lua_State *L, int index);
void push_AppResumingFromSuspend_t(lua_State *L, AppResumingFromSuspend_t val);
AssociateWithClanResult_t check_AssociateWithClanResult_t(lua_State *L, int index);
void push_AssociateWithClanResult_t(lua_State *L, AssociateWithClanResult_t val);
AvailableBeaconLocationsUpdated_t check_AvailableBeaconLocationsUpdated_t(lua_State *L, int index);
void push_AvailableBeaconLocationsUpdated_t(lua_State *L, AvailableBeaconLocationsUpdated_t val);
AvatarImageLoaded_t check_AvatarImageLoaded_t(lua_State *L, int index);
void push_AvatarImageLoaded_t(lua_State *L, AvatarImageLoaded_t val);
BroadcastUploadStart_t check_BroadcastUploadStart_t(lua_State *L, int index);
void push_BroadcastUploadStart_t(lua_State *L, BroadcastUploadStart_t val);
BroadcastUploadStop_t check_BroadcastUploadStop_t(lua_State *L, int index);
void push_BroadcastUploadStop_t(lua_State *L, BroadcastUploadStop_t val);
ChangeNumOpenSlotsCallback_t check_ChangeNumOpenSlotsCallback_t(lua_State *L, int index);
void push_ChangeNumOpenSlotsCallback_t(lua_State *L, ChangeNumOpenSlotsCallback_t val);
CheckFileSignature_t check_CheckFileSignature_t(lua_State *L, int index);
void push_CheckFileSignature_t(lua_State *L, CheckFileSignature_t val);
ClanOfficerListResponse_t check_ClanOfficerListResponse_t(lua_State *L, int index);
void push_ClanOfficerListResponse_t(lua_State *L, ClanOfficerListResponse_t val);
ClientGameServerDeny_t check_ClientGameServerDeny_t(lua_State *L, int index);
void push_ClientGameServerDeny_t(lua_State *L, ClientGameServerDeny_t val);
ComputeNewPlayerCompatibilityResult_t check_ComputeNewPlayerCompatibilityResult_t(lua_State *L, int index);
void push_ComputeNewPlayerCompatibilityResult_t(lua_State *L, ComputeNewPlayerCompatibilityResult_t val);
CreateBeaconCallback_t check_CreateBeaconCallback_t(lua_State *L, int index);
void push_CreateBeaconCallback_t(lua_State *L, CreateBeaconCallback_t val);
CreateItemResult_t check_CreateItemResult_t(lua_State *L, int index);
void push_CreateItemResult_t(lua_State *L, CreateItemResult_t val);
DeleteItemResult_t check_DeleteItemResult_t(lua_State *L, int index);
void push_DeleteItemResult_t(lua_State *L, DeleteItemResult_t val);
DlcInstalled_t check_DlcInstalled_t(lua_State *L, int index);
void push_DlcInstalled_t(lua_State *L, DlcInstalled_t val);
DownloadClanActivityCountsResult_t check_DownloadClanActivityCountsResult_t(lua_State *L, int index);
void push_DownloadClanActivityCountsResult_t(lua_State *L, DownloadClanActivityCountsResult_t val);
DownloadItemResult_t check_DownloadItemResult_t(lua_State *L, int index);
void push_DownloadItemResult_t(lua_State *L, DownloadItemResult_t val);
DurationControl_t check_DurationControl_t(lua_State *L, int index);
void push_DurationControl_t(lua_State *L, DurationControl_t val);
EncryptedAppTicketResponse_t check_EncryptedAppTicketResponse_t(lua_State *L, int index);
void push_EncryptedAppTicketResponse_t(lua_State *L, EncryptedAppTicketResponse_t val);
EquippedProfileItemsChanged_t check_EquippedProfileItemsChanged_t(lua_State *L, int index);
void push_EquippedProfileItemsChanged_t(lua_State *L, EquippedProfileItemsChanged_t val);
EquippedProfileItems_t check_EquippedProfileItems_t(lua_State *L, int index);
void push_EquippedProfileItems_t(lua_State *L, EquippedProfileItems_t val);
FavoritesListAccountsUpdated_t check_FavoritesListAccountsUpdated_t(lua_State *L, int index);
void push_FavoritesListAccountsUpdated_t(lua_State *L, FavoritesListAccountsUpdated_t val);
FavoritesListChanged_t check_FavoritesListChanged_t(lua_State *L, int index);
void push_FavoritesListChanged_t(lua_State *L, FavoritesListChanged_t val);
FileDetailsResult_t check_FileDetailsResult_t(lua_State *L, int index);
void push_FileDetailsResult_t(lua_State *L, FileDetailsResult_t val);
FilterTextDictionaryChanged_t check_FilterTextDictionaryChanged_t(lua_State *L, int index);
void push_FilterTextDictionaryChanged_t(lua_State *L, FilterTextDictionaryChanged_t val);
FloatingGamepadTextInputDismissed_t check_FloatingGamepadTextInputDismissed_t(lua_State *L, int index);
void push_FloatingGamepadTextInputDismissed_t(lua_State *L, FloatingGamepadTextInputDismissed_t val);
FriendGameInfo_t check_FriendGameInfo_t(lua_State *L, int index);
void push_FriendGameInfo_t(lua_State *L, FriendGameInfo_t val);
FriendRichPresenceUpdate_t check_FriendRichPresenceUpdate_t(lua_State *L, int index);
void push_FriendRichPresenceUpdate_t(lua_State *L, FriendRichPresenceUpdate_t val);
FriendsEnumerateFollowingList_t check_FriendsEnumerateFollowingList_t(lua_State *L, int index);
void push_FriendsEnumerateFollowingList_t(lua_State *L, FriendsEnumerateFollowingList_t val);
FriendsGetFollowerCount_t check_FriendsGetFollowerCount_t(lua_State *L, int index);
void push_FriendsGetFollowerCount_t(lua_State *L, FriendsGetFollowerCount_t val);
FriendsIsFollowing_t check_FriendsIsFollowing_t(lua_State *L, int index);
void push_FriendsIsFollowing_t(lua_State *L, FriendsIsFollowing_t val);
GSClientAchievementStatus_t check_GSClientAchievementStatus_t(lua_State *L, int index);
void push_GSClientAchievementStatus_t(lua_State *L, GSClientAchievementStatus_t val);
GSClientApprove_t check_GSClientApprove_t(lua_State *L, int index);
void push_GSClientApprove_t(lua_State *L, GSClientApprove_t val);
GSClientDeny_t check_GSClientDeny_t(lua_State *L, int index);
void push_GSClientDeny_t(lua_State *L, GSClientDeny_t val);
GSClientGroupStatus_t check_GSClientGroupStatus_t(lua_State *L, int index);
void push_GSClientGroupStatus_t(lua_State *L, GSClientGroupStatus_t val);
GSClientKick_t check_GSClientKick_t(lua_State *L, int index);
void push_GSClientKick_t(lua_State *L, GSClientKick_t val);
GSGameplayStats_t check_GSGameplayStats_t(lua_State *L, int index);
void push_GSGameplayStats_t(lua_State *L, GSGameplayStats_t val);
GSPolicyResponse_t check_GSPolicyResponse_t(lua_State *L, int index);
void push_GSPolicyResponse_t(lua_State *L, GSPolicyResponse_t val);
GSReputation_t check_GSReputation_t(lua_State *L, int index);
void push_GSReputation_t(lua_State *L, GSReputation_t val);
GSStatsReceived_t check_GSStatsReceived_t(lua_State *L, int index);
void push_GSStatsReceived_t(lua_State *L, GSStatsReceived_t val);
GSStatsStored_t check_GSStatsStored_t(lua_State *L, int index);
void push_GSStatsStored_t(lua_State *L, GSStatsStored_t val);
GSStatsUnloaded_t check_GSStatsUnloaded_t(lua_State *L, int index);
void push_GSStatsUnloaded_t(lua_State *L, GSStatsUnloaded_t val);
GameConnectedChatJoin_t check_GameConnectedChatJoin_t(lua_State *L, int index);
void push_GameConnectedChatJoin_t(lua_State *L, GameConnectedChatJoin_t val);
GameConnectedChatLeave_t check_GameConnectedChatLeave_t(lua_State *L, int index);
void push_GameConnectedChatLeave_t(lua_State *L, GameConnectedChatLeave_t val);
GameConnectedClanChatMsg_t check_GameConnectedClanChatMsg_t(lua_State *L, int index);
void push_GameConnectedClanChatMsg_t(lua_State *L, GameConnectedClanChatMsg_t val);
GameConnectedFriendChatMsg_t check_GameConnectedFriendChatMsg_t(lua_State *L, int index);
void push_GameConnectedFriendChatMsg_t(lua_State *L, GameConnectedFriendChatMsg_t val);
GameLobbyJoinRequested_t check_GameLobbyJoinRequested_t(lua_State *L, int index);
void push_GameLobbyJoinRequested_t(lua_State *L, GameLobbyJoinRequested_t val);
GameOverlayActivated_t check_GameOverlayActivated_t(lua_State *L, int index);
void push_GameOverlayActivated_t(lua_State *L, GameOverlayActivated_t val);
GameRichPresenceJoinRequested_t check_GameRichPresenceJoinRequested_t(lua_State *L, int index);
void push_GameRichPresenceJoinRequested_t(lua_State *L, GameRichPresenceJoinRequested_t val);
GameServerChangeRequested_t check_GameServerChangeRequested_t(lua_State *L, int index);
void push_GameServerChangeRequested_t(lua_State *L, GameServerChangeRequested_t val);
GameWebCallback_t check_GameWebCallback_t(lua_State *L, int index);
void push_GameWebCallback_t(lua_State *L, GameWebCallback_t val);
GamepadTextInputDismissed_t check_GamepadTextInputDismissed_t(lua_State *L, int index);
void push_GamepadTextInputDismissed_t(lua_State *L, GamepadTextInputDismissed_t val);
GetAppDependenciesResult_t check_GetAppDependenciesResult_t(lua_State *L, int index);
void push_GetAppDependenciesResult_t(lua_State *L, GetAppDependenciesResult_t val);
GetAuthSessionTicketResponse_t check_GetAuthSessionTicketResponse_t(lua_State *L, int index);
void push_GetAuthSessionTicketResponse_t(lua_State *L, GetAuthSessionTicketResponse_t val);
GetOPFSettingsResult_t check_GetOPFSettingsResult_t(lua_State *L, int index);
void push_GetOPFSettingsResult_t(lua_State *L, GetOPFSettingsResult_t val);
GetTicketForWebApiResponse_t check_GetTicketForWebApiResponse_t(lua_State *L, int index);
void push_GetTicketForWebApiResponse_t(lua_State *L, GetTicketForWebApiResponse_t val);
GetUserItemVoteResult_t check_GetUserItemVoteResult_t(lua_State *L, int index);
void push_GetUserItemVoteResult_t(lua_State *L, GetUserItemVoteResult_t val);
GetVideoURLResult_t check_GetVideoURLResult_t(lua_State *L, int index);
void push_GetVideoURLResult_t(lua_State *L, GetVideoURLResult_t val);
GlobalAchievementPercentagesReady_t check_GlobalAchievementPercentagesReady_t(lua_State *L, int index);
void push_GlobalAchievementPercentagesReady_t(lua_State *L, GlobalAchievementPercentagesReady_t val);
GlobalStatsReceived_t check_GlobalStatsReceived_t(lua_State *L, int index);
void push_GlobalStatsReceived_t(lua_State *L, GlobalStatsReceived_t val);
HTML_BrowserReady_t check_HTML_BrowserReady_t(lua_State *L, int index);
void push_HTML_BrowserReady_t(lua_State *L, HTML_BrowserReady_t val);
HTML_BrowserRestarted_t check_HTML_BrowserRestarted_t(lua_State *L, int index);
void push_HTML_BrowserRestarted_t(lua_State *L, HTML_BrowserRestarted_t val);
HTML_CanGoBackAndForward_t check_HTML_CanGoBackAndForward_t(lua_State *L, int index);
void push_HTML_CanGoBackAndForward_t(lua_State *L, HTML_CanGoBackAndForward_t val);
HTML_ChangedTitle_t check_HTML_ChangedTitle_t(lua_State *L, int index);
void push_HTML_ChangedTitle_t(lua_State *L, HTML_ChangedTitle_t val);
HTML_CloseBrowser_t check_HTML_CloseBrowser_t(lua_State *L, int index);
void push_HTML_CloseBrowser_t(lua_State *L, HTML_CloseBrowser_t val);
HTML_FileOpenDialog_t check_HTML_FileOpenDialog_t(lua_State *L, int index);
void push_HTML_FileOpenDialog_t(lua_State *L, HTML_FileOpenDialog_t val);
HTML_FinishedRequest_t check_HTML_FinishedRequest_t(lua_State *L, int index);
void push_HTML_FinishedRequest_t(lua_State *L, HTML_FinishedRequest_t val);
HTML_HideToolTip_t check_HTML_HideToolTip_t(lua_State *L, int index);
void push_HTML_HideToolTip_t(lua_State *L, HTML_HideToolTip_t val);
HTML_HorizontalScroll_t check_HTML_HorizontalScroll_t(lua_State *L, int index);
void push_HTML_HorizontalScroll_t(lua_State *L, HTML_HorizontalScroll_t val);
HTML_JSAlert_t check_HTML_JSAlert_t(lua_State *L, int index);
void push_HTML_JSAlert_t(lua_State *L, HTML_JSAlert_t val);
HTML_JSConfirm_t check_HTML_JSConfirm_t(lua_State *L, int index);
void push_HTML_JSConfirm_t(lua_State *L, HTML_JSConfirm_t val);
HTML_LinkAtPosition_t check_HTML_LinkAtPosition_t(lua_State *L, int index);
void push_HTML_LinkAtPosition_t(lua_State *L, HTML_LinkAtPosition_t val);
HTML_NeedsPaint_t check_HTML_NeedsPaint_t(lua_State *L, int index);
void push_HTML_NeedsPaint_t(lua_State *L, HTML_NeedsPaint_t val);
HTML_NewWindow_t check_HTML_NewWindow_t(lua_State *L, int index);
void push_HTML_NewWindow_t(lua_State *L, HTML_NewWindow_t val);
HTML_OpenLinkInNewTab_t check_HTML_OpenLinkInNewTab_t(lua_State *L, int index);
void push_HTML_OpenLinkInNewTab_t(lua_State *L, HTML_OpenLinkInNewTab_t val);
HTML_SearchResults_t check_HTML_SearchResults_t(lua_State *L, int index);
void push_HTML_SearchResults_t(lua_State *L, HTML_SearchResults_t val);
HTML_SetCursor_t check_HTML_SetCursor_t(lua_State *L, int index);
void push_HTML_SetCursor_t(lua_State *L, HTML_SetCursor_t val);
HTML_ShowToolTip_t check_HTML_ShowToolTip_t(lua_State *L, int index);
void push_HTML_ShowToolTip_t(lua_State *L, HTML_ShowToolTip_t val);
HTML_StartRequest_t check_HTML_StartRequest_t(lua_State *L, int index);
void push_HTML_StartRequest_t(lua_State *L, HTML_StartRequest_t val);
HTML_StatusText_t check_HTML_StatusText_t(lua_State *L, int index);
void push_HTML_StatusText_t(lua_State *L, HTML_StatusText_t val);
HTML_URLChanged_t check_HTML_URLChanged_t(lua_State *L, int index);
void push_HTML_URLChanged_t(lua_State *L, HTML_URLChanged_t val);
HTML_UpdateToolTip_t check_HTML_UpdateToolTip_t(lua_State *L, int index);
void push_HTML_UpdateToolTip_t(lua_State *L, HTML_UpdateToolTip_t val);
HTML_VerticalScroll_t check_HTML_VerticalScroll_t(lua_State *L, int index);
void push_HTML_VerticalScroll_t(lua_State *L, HTML_VerticalScroll_t val);
HTTPRequestCompleted_t check_HTTPRequestCompleted_t(lua_State *L, int index);
void push_HTTPRequestCompleted_t(lua_State *L, HTTPRequestCompleted_t val);
HTTPRequestDataReceived_t check_HTTPRequestDataReceived_t(lua_State *L, int index);
void push_HTTPRequestDataReceived_t(lua_State *L, HTTPRequestDataReceived_t val);
HTTPRequestHeadersReceived_t check_HTTPRequestHeadersReceived_t(lua_State *L, int index);
void push_HTTPRequestHeadersReceived_t(lua_State *L, HTTPRequestHeadersReceived_t val);
IPCFailure_t check_IPCFailure_t(lua_State *L, int index);
void push_IPCFailure_t(lua_State *L, IPCFailure_t val);
IPCountry_t check_IPCountry_t(lua_State *L, int index);
void push_IPCountry_t(lua_State *L, IPCountry_t val);
InputAnalogActionData_t check_InputAnalogActionData_t(lua_State *L, int index);
void push_InputAnalogActionData_t(lua_State *L, InputAnalogActionData_t val);
InputDigitalActionData_t check_InputDigitalActionData_t(lua_State *L, int index);
void push_InputDigitalActionData_t(lua_State *L, InputDigitalActionData_t val);
InputMotionData_t check_InputMotionData_t(lua_State *L, int index);
void push_InputMotionData_t(lua_State *L, InputMotionData_t val);
ItemInstalled_t check_ItemInstalled_t(lua_State *L, int index);
void push_ItemInstalled_t(lua_State *L, ItemInstalled_t val);
JoinClanChatRoomCompletionResult_t check_JoinClanChatRoomCompletionResult_t(lua_State *L, int index);
void push_JoinClanChatRoomCompletionResult_t(lua_State *L, JoinClanChatRoomCompletionResult_t val);
JoinPartyCallback_t check_JoinPartyCallback_t(lua_State *L, int index);
void push_JoinPartyCallback_t(lua_State *L, JoinPartyCallback_t val);
LeaderboardEntry_t check_LeaderboardEntry_t(lua_State *L, int index);
void push_LeaderboardEntry_t(lua_State *L, LeaderboardEntry_t val);
LeaderboardFindResult_t check_LeaderboardFindResult_t(lua_State *L, int index);
void push_LeaderboardFindResult_t(lua_State *L, LeaderboardFindResult_t val);
LeaderboardScoreUploaded_t check_LeaderboardScoreUploaded_t(lua_State *L, int index);
void push_LeaderboardScoreUploaded_t(lua_State *L, LeaderboardScoreUploaded_t val);
LeaderboardScoresDownloaded_t check_LeaderboardScoresDownloaded_t(lua_State *L, int index);
void push_LeaderboardScoresDownloaded_t(lua_State *L, LeaderboardScoresDownloaded_t val);
LeaderboardUGCSet_t check_LeaderboardUGCSet_t(lua_State *L, int index);
void push_LeaderboardUGCSet_t(lua_State *L, LeaderboardUGCSet_t val);
LicensesUpdated_t check_LicensesUpdated_t(lua_State *L, int index);
void push_LicensesUpdated_t(lua_State *L, LicensesUpdated_t val);
LobbyChatMsg_t check_LobbyChatMsg_t(lua_State *L, int index);
void push_LobbyChatMsg_t(lua_State *L, LobbyChatMsg_t val);
LobbyChatUpdate_t check_LobbyChatUpdate_t(lua_State *L, int index);
void push_LobbyChatUpdate_t(lua_State *L, LobbyChatUpdate_t val);
LobbyCreated_t check_LobbyCreated_t(lua_State *L, int index);
void push_LobbyCreated_t(lua_State *L, LobbyCreated_t val);
LobbyDataUpdate_t check_LobbyDataUpdate_t(lua_State *L, int index);
void push_LobbyDataUpdate_t(lua_State *L, LobbyDataUpdate_t val);
LobbyEnter_t check_LobbyEnter_t(lua_State *L, int index);
void push_LobbyEnter_t(lua_State *L, LobbyEnter_t val);
LobbyGameCreated_t check_LobbyGameCreated_t(lua_State *L, int index);
void push_LobbyGameCreated_t(lua_State *L, LobbyGameCreated_t val);
LobbyInvite_t check_LobbyInvite_t(lua_State *L, int index);
void push_LobbyInvite_t(lua_State *L, LobbyInvite_t val);
LobbyKicked_t check_LobbyKicked_t(lua_State *L, int index);
void push_LobbyKicked_t(lua_State *L, LobbyKicked_t val);
LobbyMatchList_t check_LobbyMatchList_t(lua_State *L, int index);
void push_LobbyMatchList_t(lua_State *L, LobbyMatchList_t val);
LowBatteryPower_t check_LowBatteryPower_t(lua_State *L, int index);
void push_LowBatteryPower_t(lua_State *L, LowBatteryPower_t val);
MarketEligibilityResponse_t check_MarketEligibilityResponse_t(lua_State *L, int index);
void push_MarketEligibilityResponse_t(lua_State *L, MarketEligibilityResponse_t val);
MatchMakingKeyValuePair_t check_MatchMakingKeyValuePair_t(lua_State *L, int index);
void push_MatchMakingKeyValuePair_t(lua_State *L, MatchMakingKeyValuePair_t val);
MicroTxnAuthorizationResponse_t check_MicroTxnAuthorizationResponse_t(lua_State *L, int index);
void push_MicroTxnAuthorizationResponse_t(lua_State *L, MicroTxnAuthorizationResponse_t val);
NewUrlLaunchParameters_t check_NewUrlLaunchParameters_t(lua_State *L, int index);
void push_NewUrlLaunchParameters_t(lua_State *L, NewUrlLaunchParameters_t val);
NumberOfCurrentPlayers_t check_NumberOfCurrentPlayers_t(lua_State *L, int index);
void push_NumberOfCurrentPlayers_t(lua_State *L, NumberOfCurrentPlayers_t val);
OverlayBrowserProtocolNavigation_t check_OverlayBrowserProtocolNavigation_t(lua_State *L, int index);
void push_OverlayBrowserProtocolNavigation_t(lua_State *L, OverlayBrowserProtocolNavigation_t val);
P2PSessionConnectFail_t check_P2PSessionConnectFail_t(lua_State *L, int index);
void push_P2PSessionConnectFail_t(lua_State *L, P2PSessionConnectFail_t val);
P2PSessionRequest_t check_P2PSessionRequest_t(lua_State *L, int index);
void push_P2PSessionRequest_t(lua_State *L, P2PSessionRequest_t val);
P2PSessionState_t check_P2PSessionState_t(lua_State *L, int index);
void push_P2PSessionState_t(lua_State *L, P2PSessionState_t val);
PersonaStateChange_t check_PersonaStateChange_t(lua_State *L, int index);
void push_PersonaStateChange_t(lua_State *L, PersonaStateChange_t val);
PlaybackStatusHasChanged_t check_PlaybackStatusHasChanged_t(lua_State *L, int index);
void push_PlaybackStatusHasChanged_t(lua_State *L, PlaybackStatusHasChanged_t val);
RemotePlayInputKey_t check_RemotePlayInputKey_t(lua_State *L, int index);
void push_RemotePlayInputKey_t(lua_State *L, RemotePlayInputKey_t val);
RemotePlayInputMouseMotion_t check_RemotePlayInputMouseMotion_t(lua_State *L, int index);
void push_RemotePlayInputMouseMotion_t(lua_State *L, RemotePlayInputMouseMotion_t val);
RemotePlayInputMouseWheel_t check_RemotePlayInputMouseWheel_t(lua_State *L, int index);
void push_RemotePlayInputMouseWheel_t(lua_State *L, RemotePlayInputMouseWheel_t val);
RemotePlayInput_t check_RemotePlayInput_t(lua_State *L, int index);
void push_RemotePlayInput_t(lua_State *L, RemotePlayInput_t val);
RemoteStorageDeletePublishedFileResult_t check_RemoteStorageDeletePublishedFileResult_t(lua_State *L, int index);
void push_RemoteStorageDeletePublishedFileResult_t(lua_State *L, RemoteStorageDeletePublishedFileResult_t val);
RemoteStorageDownloadUGCResult_t check_RemoteStorageDownloadUGCResult_t(lua_State *L, int index);
void push_RemoteStorageDownloadUGCResult_t(lua_State *L, RemoteStorageDownloadUGCResult_t val);
RemoteStorageEnumeratePublishedFilesByUserActionResult_t check_RemoteStorageEnumeratePublishedFilesByUserActionResult_t(lua_State *L, int index);
void push_RemoteStorageEnumeratePublishedFilesByUserActionResult_t(lua_State *L, RemoteStorageEnumeratePublishedFilesByUserActionResult_t val);
RemoteStorageEnumerateUserPublishedFilesResult_t check_RemoteStorageEnumerateUserPublishedFilesResult_t(lua_State *L, int index);
void push_RemoteStorageEnumerateUserPublishedFilesResult_t(lua_State *L, RemoteStorageEnumerateUserPublishedFilesResult_t val);
RemoteStorageEnumerateUserSharedWorkshopFilesResult_t check_RemoteStorageEnumerateUserSharedWorkshopFilesResult_t(lua_State *L, int index);
void push_RemoteStorageEnumerateUserSharedWorkshopFilesResult_t(lua_State *L, RemoteStorageEnumerateUserSharedWorkshopFilesResult_t val);
RemoteStorageEnumerateUserSubscribedFilesResult_t check_RemoteStorageEnumerateUserSubscribedFilesResult_t(lua_State *L, int index);
void push_RemoteStorageEnumerateUserSubscribedFilesResult_t(lua_State *L, RemoteStorageEnumerateUserSubscribedFilesResult_t val);
RemoteStorageEnumerateWorkshopFilesResult_t check_RemoteStorageEnumerateWorkshopFilesResult_t(lua_State *L, int index);
void push_RemoteStorageEnumerateWorkshopFilesResult_t(lua_State *L, RemoteStorageEnumerateWorkshopFilesResult_t val);
RemoteStorageFileReadAsyncComplete_t check_RemoteStorageFileReadAsyncComplete_t(lua_State *L, int index);
void push_RemoteStorageFileReadAsyncComplete_t(lua_State *L, RemoteStorageFileReadAsyncComplete_t val);
RemoteStorageFileShareResult_t check_RemoteStorageFileShareResult_t(lua_State *L, int index);
void push_RemoteStorageFileShareResult_t(lua_State *L, RemoteStorageFileShareResult_t val);
RemoteStorageFileWriteAsyncComplete_t check_RemoteStorageFileWriteAsyncComplete_t(lua_State *L, int index);
void push_RemoteStorageFileWriteAsyncComplete_t(lua_State *L, RemoteStorageFileWriteAsyncComplete_t val);
RemoteStorageGetPublishedFileDetailsResult_t check_RemoteStorageGetPublishedFileDetailsResult_t(lua_State *L, int index);
void push_RemoteStorageGetPublishedFileDetailsResult_t(lua_State *L, RemoteStorageGetPublishedFileDetailsResult_t val);
RemoteStorageGetPublishedItemVoteDetailsResult_t check_RemoteStorageGetPublishedItemVoteDetailsResult_t(lua_State *L, int index);
void push_RemoteStorageGetPublishedItemVoteDetailsResult_t(lua_State *L, RemoteStorageGetPublishedItemVoteDetailsResult_t val);
RemoteStorageLocalFileChange_t check_RemoteStorageLocalFileChange_t(lua_State *L, int index);
void push_RemoteStorageLocalFileChange_t(lua_State *L, RemoteStorageLocalFileChange_t val);
RemoteStoragePublishFileProgress_t check_RemoteStoragePublishFileProgress_t(lua_State *L, int index);
void push_RemoteStoragePublishFileProgress_t(lua_State *L, RemoteStoragePublishFileProgress_t val);
RemoteStoragePublishFileResult_t check_RemoteStoragePublishFileResult_t(lua_State *L, int index);
void push_RemoteStoragePublishFileResult_t(lua_State *L, RemoteStoragePublishFileResult_t val);
RemoteStoragePublishedFileDeleted_t check_RemoteStoragePublishedFileDeleted_t(lua_State *L, int index);
void push_RemoteStoragePublishedFileDeleted_t(lua_State *L, RemoteStoragePublishedFileDeleted_t val);
RemoteStoragePublishedFileSubscribed_t check_RemoteStoragePublishedFileSubscribed_t(lua_State *L, int index);
void push_RemoteStoragePublishedFileSubscribed_t(lua_State *L, RemoteStoragePublishedFileSubscribed_t val);
RemoteStoragePublishedFileUnsubscribed_t check_RemoteStoragePublishedFileUnsubscribed_t(lua_State *L, int index);
void push_RemoteStoragePublishedFileUnsubscribed_t(lua_State *L, RemoteStoragePublishedFileUnsubscribed_t val);
RemoteStoragePublishedFileUpdated_t check_RemoteStoragePublishedFileUpdated_t(lua_State *L, int index);
void push_RemoteStoragePublishedFileUpdated_t(lua_State *L, RemoteStoragePublishedFileUpdated_t val);
RemoteStorageSetUserPublishedFileActionResult_t check_RemoteStorageSetUserPublishedFileActionResult_t(lua_State *L, int index);
void push_RemoteStorageSetUserPublishedFileActionResult_t(lua_State *L, RemoteStorageSetUserPublishedFileActionResult_t val);
RemoteStorageSubscribePublishedFileResult_t check_RemoteStorageSubscribePublishedFileResult_t(lua_State *L, int index);
void push_RemoteStorageSubscribePublishedFileResult_t(lua_State *L, RemoteStorageSubscribePublishedFileResult_t val);
RemoteStorageUnsubscribePublishedFileResult_t check_RemoteStorageUnsubscribePublishedFileResult_t(lua_State *L, int index);
void push_RemoteStorageUnsubscribePublishedFileResult_t(lua_State *L, RemoteStorageUnsubscribePublishedFileResult_t val);
RemoteStorageUpdatePublishedFileResult_t check_RemoteStorageUpdatePublishedFileResult_t(lua_State *L, int index);
void push_RemoteStorageUpdatePublishedFileResult_t(lua_State *L, RemoteStorageUpdatePublishedFileResult_t val);
RemoteStorageUpdateUserPublishedItemVoteResult_t check_RemoteStorageUpdateUserPublishedItemVoteResult_t(lua_State *L, int index);
void push_RemoteStorageUpdateUserPublishedItemVoteResult_t(lua_State *L, RemoteStorageUpdateUserPublishedItemVoteResult_t val);
RemoteStorageUserVoteDetails_t check_RemoteStorageUserVoteDetails_t(lua_State *L, int index);
void push_RemoteStorageUserVoteDetails_t(lua_State *L, RemoteStorageUserVoteDetails_t val);
RemoveAppDependencyResult_t check_RemoveAppDependencyResult_t(lua_State *L, int index);
void push_RemoveAppDependencyResult_t(lua_State *L, RemoveAppDependencyResult_t val);
RemoveUGCDependencyResult_t check_RemoveUGCDependencyResult_t(lua_State *L, int index);
void push_RemoveUGCDependencyResult_t(lua_State *L, RemoveUGCDependencyResult_t val);
ReservationNotificationCallback_t check_ReservationNotificationCallback_t(lua_State *L, int index);
void push_ReservationNotificationCallback_t(lua_State *L, ReservationNotificationCallback_t val);
ScreenshotReady_t check_ScreenshotReady_t(lua_State *L, int index);
void push_ScreenshotReady_t(lua_State *L, ScreenshotReady_t val);
ScreenshotRequested_t check_ScreenshotRequested_t(lua_State *L, int index);
void push_ScreenshotRequested_t(lua_State *L, ScreenshotRequested_t val);
SetUserItemVoteResult_t check_SetUserItemVoteResult_t(lua_State *L, int index);
void push_SetUserItemVoteResult_t(lua_State *L, SetUserItemVoteResult_t val);
SocketStatusCallback_t check_SocketStatusCallback_t(lua_State *L, int index);
void push_SocketStatusCallback_t(lua_State *L, SocketStatusCallback_t val);
StartPlaytimeTrackingResult_t check_StartPlaytimeTrackingResult_t(lua_State *L, int index);
void push_StartPlaytimeTrackingResult_t(lua_State *L, StartPlaytimeTrackingResult_t val);
SteamAPICallCompleted_t check_SteamAPICallCompleted_t(lua_State *L, int index);
void push_SteamAPICallCompleted_t(lua_State *L, SteamAPICallCompleted_t val);
SteamIPAddress_t check_SteamIPAddress_t(lua_State *L, int index);
void push_SteamIPAddress_t(lua_State *L, SteamIPAddress_t val);
SteamInputActionEvent_t check_SteamInputActionEvent_t(lua_State *L, int index);
void push_SteamInputActionEvent_t(lua_State *L, SteamInputActionEvent_t val);
SteamInputConfigurationLoaded_t check_SteamInputConfigurationLoaded_t(lua_State *L, int index);
void push_SteamInputConfigurationLoaded_t(lua_State *L, SteamInputConfigurationLoaded_t val);
SteamInputDeviceConnected_t check_SteamInputDeviceConnected_t(lua_State *L, int index);
void push_SteamInputDeviceConnected_t(lua_State *L, SteamInputDeviceConnected_t val);
SteamInputDeviceDisconnected_t check_SteamInputDeviceDisconnected_t(lua_State *L, int index);
void push_SteamInputDeviceDisconnected_t(lua_State *L, SteamInputDeviceDisconnected_t val);
SteamInputGamepadSlotChange_t check_SteamInputGamepadSlotChange_t(lua_State *L, int index);
void push_SteamInputGamepadSlotChange_t(lua_State *L, SteamInputGamepadSlotChange_t val);
SteamInventoryDefinitionUpdate_t check_SteamInventoryDefinitionUpdate_t(lua_State *L, int index);
void push_SteamInventoryDefinitionUpdate_t(lua_State *L, SteamInventoryDefinitionUpdate_t val);
SteamInventoryEligiblePromoItemDefIDs_t check_SteamInventoryEligiblePromoItemDefIDs_t(lua_State *L, int index);
void push_SteamInventoryEligiblePromoItemDefIDs_t(lua_State *L, SteamInventoryEligiblePromoItemDefIDs_t val);
SteamInventoryFullUpdate_t check_SteamInventoryFullUpdate_t(lua_State *L, int index);
void push_SteamInventoryFullUpdate_t(lua_State *L, SteamInventoryFullUpdate_t val);
SteamInventoryRequestPricesResult_t check_SteamInventoryRequestPricesResult_t(lua_State *L, int index);
void push_SteamInventoryRequestPricesResult_t(lua_State *L, SteamInventoryRequestPricesResult_t val);
SteamInventoryResultReady_t check_SteamInventoryResultReady_t(lua_State *L, int index);
void push_SteamInventoryResultReady_t(lua_State *L, SteamInventoryResultReady_t val);
SteamInventoryStartPurchaseResult_t check_SteamInventoryStartPurchaseResult_t(lua_State *L, int index);
void push_SteamInventoryStartPurchaseResult_t(lua_State *L, SteamInventoryStartPurchaseResult_t val);
SteamItemDetails_t check_SteamItemDetails_t(lua_State *L, int index);
void push_SteamItemDetails_t(lua_State *L, SteamItemDetails_t val);
SteamNetAuthenticationStatus_t check_SteamNetAuthenticationStatus_t(lua_State *L, int index);
void push_SteamNetAuthenticationStatus_t(lua_State *L, SteamNetAuthenticationStatus_t val);
SteamNetConnectionInfo_t check_SteamNetConnectionInfo_t(lua_State *L, int index);
void push_SteamNetConnectionInfo_t(lua_State *L, SteamNetConnectionInfo_t val);
SteamNetConnectionRealTimeLaneStatus_t check_SteamNetConnectionRealTimeLaneStatus_t(lua_State *L, int index);
void push_SteamNetConnectionRealTimeLaneStatus_t(lua_State *L, SteamNetConnectionRealTimeLaneStatus_t val);
SteamNetConnectionRealTimeStatus_t check_SteamNetConnectionRealTimeStatus_t(lua_State *L, int index);
void push_SteamNetConnectionRealTimeStatus_t(lua_State *L, SteamNetConnectionRealTimeStatus_t val);
SteamNetConnectionStatusChangedCallback_t check_SteamNetConnectionStatusChangedCallback_t(lua_State *L, int index);
void push_SteamNetConnectionStatusChangedCallback_t(lua_State *L, SteamNetConnectionStatusChangedCallback_t val);
SteamNetworkPingLocation_t check_SteamNetworkPingLocation_t(lua_State *L, int index);
void push_SteamNetworkPingLocation_t(lua_State *L, SteamNetworkPingLocation_t val);
SteamNetworkingConfigValue_t check_SteamNetworkingConfigValue_t(lua_State *L, int index);
void push_SteamNetworkingConfigValue_t(lua_State *L, SteamNetworkingConfigValue_t val);
SteamNetworkingFakeIPResult_t check_SteamNetworkingFakeIPResult_t(lua_State *L, int index);
void push_SteamNetworkingFakeIPResult_t(lua_State *L, SteamNetworkingFakeIPResult_t val);
SteamNetworkingIPAddr check_SteamNetworkingIPAddr(lua_State *L, int index);
void push_SteamNetworkingIPAddr(lua_State *L, SteamNetworkingIPAddr val);
SteamNetworkingIdentity check_SteamNetworkingIdentity(lua_State *L, int index);
void push_SteamNetworkingIdentity(lua_State *L, SteamNetworkingIdentity val);
SteamNetworkingMessagesSessionFailed_t check_SteamNetworkingMessagesSessionFailed_t(lua_State *L, int index);
void push_SteamNetworkingMessagesSessionFailed_t(lua_State *L, SteamNetworkingMessagesSessionFailed_t val);
SteamNetworkingMessagesSessionRequest_t check_SteamNetworkingMessagesSessionRequest_t(lua_State *L, int index);
void push_SteamNetworkingMessagesSessionRequest_t(lua_State *L, SteamNetworkingMessagesSessionRequest_t val);
SteamParamStringArray_t check_SteamParamStringArray_t(lua_State *L, int index);
void push_SteamParamStringArray_t(lua_State *L, SteamParamStringArray_t val);
SteamParentalSettingsChanged_t check_SteamParentalSettingsChanged_t(lua_State *L, int index);
void push_SteamParentalSettingsChanged_t(lua_State *L, SteamParentalSettingsChanged_t val);
SteamPartyBeaconLocation_t check_SteamPartyBeaconLocation_t(lua_State *L, int index);
void push_SteamPartyBeaconLocation_t(lua_State *L, SteamPartyBeaconLocation_t val);
SteamRelayNetworkStatus_t check_SteamRelayNetworkStatus_t(lua_State *L, int index);
void push_SteamRelayNetworkStatus_t(lua_State *L, SteamRelayNetworkStatus_t val);
SteamRemotePlaySessionConnected_t check_SteamRemotePlaySessionConnected_t(lua_State *L, int index);
void push_SteamRemotePlaySessionConnected_t(lua_State *L, SteamRemotePlaySessionConnected_t val);
SteamRemotePlaySessionDisconnected_t check_SteamRemotePlaySessionDisconnected_t(lua_State *L, int index);
void push_SteamRemotePlaySessionDisconnected_t(lua_State *L, SteamRemotePlaySessionDisconnected_t val);
SteamRemotePlayTogetherGuestInvite_t check_SteamRemotePlayTogetherGuestInvite_t(lua_State *L, int index);
void push_SteamRemotePlayTogetherGuestInvite_t(lua_State *L, SteamRemotePlayTogetherGuestInvite_t val);
SteamServerConnectFailure_t check_SteamServerConnectFailure_t(lua_State *L, int index);
void push_SteamServerConnectFailure_t(lua_State *L, SteamServerConnectFailure_t val);
SteamServersConnected_t check_SteamServersConnected_t(lua_State *L, int index);
void push_SteamServersConnected_t(lua_State *L, SteamServersConnected_t val);
SteamServersDisconnected_t check_SteamServersDisconnected_t(lua_State *L, int index);
void push_SteamServersDisconnected_t(lua_State *L, SteamServersDisconnected_t val);
SteamShutdown_t check_SteamShutdown_t(lua_State *L, int index);
void push_SteamShutdown_t(lua_State *L, SteamShutdown_t val);
SteamTimelineEventRecordingExists_t check_SteamTimelineEventRecordingExists_t(lua_State *L, int index);
void push_SteamTimelineEventRecordingExists_t(lua_State *L, SteamTimelineEventRecordingExists_t val);
SteamTimelineGamePhaseRecordingExists_t check_SteamTimelineGamePhaseRecordingExists_t(lua_State *L, int index);
void push_SteamTimelineGamePhaseRecordingExists_t(lua_State *L, SteamTimelineGamePhaseRecordingExists_t val);
SteamUGCDetails_t check_SteamUGCDetails_t(lua_State *L, int index);
void push_SteamUGCDetails_t(lua_State *L, SteamUGCDetails_t val);
SteamUGCQueryCompleted_t check_SteamUGCQueryCompleted_t(lua_State *L, int index);
void push_SteamUGCQueryCompleted_t(lua_State *L, SteamUGCQueryCompleted_t val);
SteamUGCRequestUGCDetailsResult_t check_SteamUGCRequestUGCDetailsResult_t(lua_State *L, int index);
void push_SteamUGCRequestUGCDetailsResult_t(lua_State *L, SteamUGCRequestUGCDetailsResult_t val);
StopPlaytimeTrackingResult_t check_StopPlaytimeTrackingResult_t(lua_State *L, int index);
void push_StopPlaytimeTrackingResult_t(lua_State *L, StopPlaytimeTrackingResult_t val);
StoreAuthURLResponse_t check_StoreAuthURLResponse_t(lua_State *L, int index);
void push_StoreAuthURLResponse_t(lua_State *L, StoreAuthURLResponse_t val);
SubmitItemUpdateResult_t check_SubmitItemUpdateResult_t(lua_State *L, int index);
void push_SubmitItemUpdateResult_t(lua_State *L, SubmitItemUpdateResult_t val);
TimedTrialStatus_t check_TimedTrialStatus_t(lua_State *L, int index);
void push_TimedTrialStatus_t(lua_State *L, TimedTrialStatus_t val);
UnreadChatMessagesChanged_t check_UnreadChatMessagesChanged_t(lua_State *L, int index);
void push_UnreadChatMessagesChanged_t(lua_State *L, UnreadChatMessagesChanged_t val);
UserAchievementIconFetched_t check_UserAchievementIconFetched_t(lua_State *L, int index);
void push_UserAchievementIconFetched_t(lua_State *L, UserAchievementIconFetched_t val);
UserAchievementStored_t check_UserAchievementStored_t(lua_State *L, int index);
void push_UserAchievementStored_t(lua_State *L, UserAchievementStored_t val);
UserFavoriteItemsListChanged_t check_UserFavoriteItemsListChanged_t(lua_State *L, int index);
void push_UserFavoriteItemsListChanged_t(lua_State *L, UserFavoriteItemsListChanged_t val);
UserStatsReceived_t check_UserStatsReceived_t(lua_State *L, int index);
void push_UserStatsReceived_t(lua_State *L, UserStatsReceived_t val);
UserStatsStored_t check_UserStatsStored_t(lua_State *L, int index);
void push_UserStatsStored_t(lua_State *L, UserStatsStored_t val);
UserStatsUnloaded_t check_UserStatsUnloaded_t(lua_State *L, int index);
void push_UserStatsUnloaded_t(lua_State *L, UserStatsUnloaded_t val);
UserSubscribedItemsListChanged_t check_UserSubscribedItemsListChanged_t(lua_State *L, int index);
void push_UserSubscribedItemsListChanged_t(lua_State *L, UserSubscribedItemsListChanged_t val);
ValidateAuthTicketResponse_t check_ValidateAuthTicketResponse_t(lua_State *L, int index);
void push_ValidateAuthTicketResponse_t(lua_State *L, ValidateAuthTicketResponse_t val);
VolumeHasChanged_t check_VolumeHasChanged_t(lua_State *L, int index);
void push_VolumeHasChanged_t(lua_State *L, VolumeHasChanged_t val);
WorkshopEULAStatus_t check_WorkshopEULAStatus_t(lua_State *L, int index);
void push_WorkshopEULAStatus_t(lua_State *L, WorkshopEULAStatus_t val);
gameserveritem_t check_gameserveritem_t(lua_State *L, int index);
void push_gameserveritem_t(lua_State *L, gameserveritem_t val);
servernetadr_t check_servernetadr_t(lua_State *L, int index);
void push_servernetadr_t(lua_State *L, servernetadr_t val);
ActiveBeaconsUpdated_t *check_ActiveBeaconsUpdated_t_ptr(lua_State *L, int index);
AddAppDependencyResult_t *check_AddAppDependencyResult_t_ptr(lua_State *L, int index);
AddUGCDependencyResult_t *check_AddUGCDependencyResult_t_ptr(lua_State *L, int index);
AppProofOfPurchaseKeyResponse_t *check_AppProofOfPurchaseKeyResponse_t_ptr(lua_State *L, int index);
AppResumingFromSuspend_t *check_AppResumingFromSuspend_t_ptr(lua_State *L, int index);
AssociateWithClanResult_t *check_AssociateWithClanResult_t_ptr(lua_State *L, int index);
AvailableBeaconLocationsUpdated_t *check_AvailableBeaconLocationsUpdated_t_ptr(lua_State *L, int index);
AvatarImageLoaded_t *check_AvatarImageLoaded_t_ptr(lua_State *L, int index);
BroadcastUploadStart_t *check_BroadcastUploadStart_t_ptr(lua_State *L, int index);
BroadcastUploadStop_t *check_BroadcastUploadStop_t_ptr(lua_State *L, int index);
ChangeNumOpenSlotsCallback_t *check_ChangeNumOpenSlotsCallback_t_ptr(lua_State *L, int index);
CheckFileSignature_t *check_CheckFileSignature_t_ptr(lua_State *L, int index);
ClanOfficerListResponse_t *check_ClanOfficerListResponse_t_ptr(lua_State *L, int index);
ClientGameServerDeny_t *check_ClientGameServerDeny_t_ptr(lua_State *L, int index);
ComputeNewPlayerCompatibilityResult_t *check_ComputeNewPlayerCompatibilityResult_t_ptr(lua_State *L, int index);
CreateBeaconCallback_t *check_CreateBeaconCallback_t_ptr(lua_State *L, int index);
CreateItemResult_t *check_CreateItemResult_t_ptr(lua_State *L, int index);
DeleteItemResult_t *check_DeleteItemResult_t_ptr(lua_State *L, int index);
DlcInstalled_t *check_DlcInstalled_t_ptr(lua_State *L, int index);
DownloadClanActivityCountsResult_t *check_DownloadClanActivityCountsResult_t_ptr(lua_State *L, int index);
DownloadItemResult_t *check_DownloadItemResult_t_ptr(lua_State *L, int index);
DurationControl_t *check_DurationControl_t_ptr(lua_State *L, int index);
EncryptedAppTicketResponse_t *check_EncryptedAppTicketResponse_t_ptr(lua_State *L, int index);
EquippedProfileItemsChanged_t *check_EquippedProfileItemsChanged_t_ptr(lua_State *L, int index);
EquippedProfileItems_t *check_EquippedProfileItems_t_ptr(lua_State *L, int index);
FavoritesListAccountsUpdated_t *check_FavoritesListAccountsUpdated_t_ptr(lua_State *L, int index);
FavoritesListChanged_t *check_FavoritesListChanged_t_ptr(lua_State *L, int index);
FileDetailsResult_t *check_FileDetailsResult_t_ptr(lua_State *L, int index);
FilterTextDictionaryChanged_t *check_FilterTextDictionaryChanged_t_ptr(lua_State *L, int index);
FloatingGamepadTextInputDismissed_t *check_FloatingGamepadTextInputDismissed_t_ptr(lua_State *L, int index);
FriendGameInfo_t *check_FriendGameInfo_t_ptr(lua_State *L, int index);
FriendRichPresenceUpdate_t *check_FriendRichPresenceUpdate_t_ptr(lua_State *L, int index);
FriendsEnumerateFollowingList_t *check_FriendsEnumerateFollowingList_t_ptr(lua_State *L, int index);
FriendsGetFollowerCount_t *check_FriendsGetFollowerCount_t_ptr(lua_State *L, int index);
FriendsIsFollowing_t *check_FriendsIsFollowing_t_ptr(lua_State *L, int index);
GSClientAchievementStatus_t *check_GSClientAchievementStatus_t_ptr(lua_State *L, int index);
GSClientApprove_t *check_GSClientApprove_t_ptr(lua_State *L, int index);
GSClientDeny_t *check_GSClientDeny_t_ptr(lua_State *L, int index);
GSClientGroupStatus_t *check_GSClientGroupStatus_t_ptr(lua_State *L, int index);
GSClientKick_t *check_GSClientKick_t_ptr(lua_State *L, int index);
GSGameplayStats_t *check_GSGameplayStats_t_ptr(lua_State *L, int index);
GSPolicyResponse_t *check_GSPolicyResponse_t_ptr(lua_State *L, int index);
GSReputation_t *check_GSReputation_t_ptr(lua_State *L, int index);
GSStatsReceived_t *check_GSStatsReceived_t_ptr(lua_State *L, int index);
GSStatsStored_t *check_GSStatsStored_t_ptr(lua_State *L, int index);
GSStatsUnloaded_t *check_GSStatsUnloaded_t_ptr(lua_State *L, int index);
GameConnectedChatJoin_t *check_GameConnectedChatJoin_t_ptr(lua_State *L, int index);
GameConnectedChatLeave_t *check_GameConnectedChatLeave_t_ptr(lua_State *L, int index);
GameConnectedClanChatMsg_t *check_GameConnectedClanChatMsg_t_ptr(lua_State *L, int index);
GameConnectedFriendChatMsg_t *check_GameConnectedFriendChatMsg_t_ptr(lua_State *L, int index);
GameLobbyJoinRequested_t *check_GameLobbyJoinRequested_t_ptr(lua_State *L, int index);
GameOverlayActivated_t *check_GameOverlayActivated_t_ptr(lua_State *L, int index);
GameRichPresenceJoinRequested_t *check_GameRichPresenceJoinRequested_t_ptr(lua_State *L, int index);
GameServerChangeRequested_t *check_GameServerChangeRequested_t_ptr(lua_State *L, int index);
GameWebCallback_t *check_GameWebCallback_t_ptr(lua_State *L, int index);
GamepadTextInputDismissed_t *check_GamepadTextInputDismissed_t_ptr(lua_State *L, int index);
GetAppDependenciesResult_t *check_GetAppDependenciesResult_t_ptr(lua_State *L, int index);
GetAuthSessionTicketResponse_t *check_GetAuthSessionTicketResponse_t_ptr(lua_State *L, int index);
GetOPFSettingsResult_t *check_GetOPFSettingsResult_t_ptr(lua_State *L, int index);
GetTicketForWebApiResponse_t *check_GetTicketForWebApiResponse_t_ptr(lua_State *L, int index);
GetUserItemVoteResult_t *check_GetUserItemVoteResult_t_ptr(lua_State *L, int index);
GetVideoURLResult_t *check_GetVideoURLResult_t_ptr(lua_State *L, int index);
GlobalAchievementPercentagesReady_t *check_GlobalAchievementPercentagesReady_t_ptr(lua_State *L, int index);
GlobalStatsReceived_t *check_GlobalStatsReceived_t_ptr(lua_State *L, int index);
HTML_BrowserReady_t *check_HTML_BrowserReady_t_ptr(lua_State *L, int index);
HTML_BrowserRestarted_t *check_HTML_BrowserRestarted_t_ptr(lua_State *L, int index);
HTML_CanGoBackAndForward_t *check_HTML_CanGoBackAndForward_t_ptr(lua_State *L, int index);
HTML_ChangedTitle_t *check_HTML_ChangedTitle_t_ptr(lua_State *L, int index);
HTML_CloseBrowser_t *check_HTML_CloseBrowser_t_ptr(lua_State *L, int index);
HTML_FileOpenDialog_t *check_HTML_FileOpenDialog_t_ptr(lua_State *L, int index);
HTML_FinishedRequest_t *check_HTML_FinishedRequest_t_ptr(lua_State *L, int index);
HTML_HideToolTip_t *check_HTML_HideToolTip_t_ptr(lua_State *L, int index);
HTML_HorizontalScroll_t *check_HTML_HorizontalScroll_t_ptr(lua_State *L, int index);
HTML_JSAlert_t *check_HTML_JSAlert_t_ptr(lua_State *L, int index);
HTML_JSConfirm_t *check_HTML_JSConfirm_t_ptr(lua_State *L, int index);
HTML_LinkAtPosition_t *check_HTML_LinkAtPosition_t_ptr(lua_State *L, int index);
HTML_NeedsPaint_t *check_HTML_NeedsPaint_t_ptr(lua_State *L, int index);
HTML_NewWindow_t *check_HTML_NewWindow_t_ptr(lua_State *L, int index);
HTML_OpenLinkInNewTab_t *check_HTML_OpenLinkInNewTab_t_ptr(lua_State *L, int index);
HTML_SearchResults_t *check_HTML_SearchResults_t_ptr(lua_State *L, int index);
HTML_SetCursor_t *check_HTML_SetCursor_t_ptr(lua_State *L, int index);
HTML_ShowToolTip_t *check_HTML_ShowToolTip_t_ptr(lua_State *L, int index);
HTML_StartRequest_t *check_HTML_StartRequest_t_ptr(lua_State *L, int index);
HTML_StatusText_t *check_HTML_StatusText_t_ptr(lua_State *L, int index);
HTML_URLChanged_t *check_HTML_URLChanged_t_ptr(lua_State *L, int index);
HTML_UpdateToolTip_t *check_HTML_UpdateToolTip_t_ptr(lua_State *L, int index);
HTML_VerticalScroll_t *check_HTML_VerticalScroll_t_ptr(lua_State *L, int index);
HTTPRequestCompleted_t *check_HTTPRequestCompleted_t_ptr(lua_State *L, int index);
HTTPRequestDataReceived_t *check_HTTPRequestDataReceived_t_ptr(lua_State *L, int index);
HTTPRequestHeadersReceived_t *check_HTTPRequestHeadersReceived_t_ptr(lua_State *L, int index);
IPCFailure_t *check_IPCFailure_t_ptr(lua_State *L, int index);
IPCountry_t *check_IPCountry_t_ptr(lua_State *L, int index);
InputAnalogActionData_t *check_InputAnalogActionData_t_ptr(lua_State *L, int index);
InputDigitalActionData_t *check_InputDigitalActionData_t_ptr(lua_State *L, int index);
InputMotionData_t *check_InputMotionData_t_ptr(lua_State *L, int index);
ItemInstalled_t *check_ItemInstalled_t_ptr(lua_State *L, int index);
JoinClanChatRoomCompletionResult_t *check_JoinClanChatRoomCompletionResult_t_ptr(lua_State *L, int index);
JoinPartyCallback_t *check_JoinPartyCallback_t_ptr(lua_State *L, int index);
LeaderboardEntry_t *check_LeaderboardEntry_t_ptr(lua_State *L, int index);
LeaderboardFindResult_t *check_LeaderboardFindResult_t_ptr(lua_State *L, int index);
LeaderboardScoreUploaded_t *check_LeaderboardScoreUploaded_t_ptr(lua_State *L, int index);
LeaderboardScoresDownloaded_t *check_LeaderboardScoresDownloaded_t_ptr(lua_State *L, int index);
LeaderboardUGCSet_t *check_LeaderboardUGCSet_t_ptr(lua_State *L, int index);
LicensesUpdated_t *check_LicensesUpdated_t_ptr(lua_State *L, int index);
LobbyChatMsg_t *check_LobbyChatMsg_t_ptr(lua_State *L, int index);
LobbyChatUpdate_t *check_LobbyChatUpdate_t_ptr(lua_State *L, int index);
LobbyCreated_t *check_LobbyCreated_t_ptr(lua_State *L, int index);
LobbyDataUpdate_t *check_LobbyDataUpdate_t_ptr(lua_State *L, int index);
LobbyEnter_t *check_LobbyEnter_t_ptr(lua_State *L, int index);
LobbyGameCreated_t *check_LobbyGameCreated_t_ptr(lua_State *L, int index);
LobbyInvite_t *check_LobbyInvite_t_ptr(lua_State *L, int index);
LobbyKicked_t *check_LobbyKicked_t_ptr(lua_State *L, int index);
LobbyMatchList_t *check_LobbyMatchList_t_ptr(lua_State *L, int index);
LowBatteryPower_t *check_LowBatteryPower_t_ptr(lua_State *L, int index);
MarketEligibilityResponse_t *check_MarketEligibilityResponse_t_ptr(lua_State *L, int index);
MatchMakingKeyValuePair_t *check_MatchMakingKeyValuePair_t_ptr(lua_State *L, int index);
MicroTxnAuthorizationResponse_t *check_MicroTxnAuthorizationResponse_t_ptr(lua_State *L, int index);
NewUrlLaunchParameters_t *check_NewUrlLaunchParameters_t_ptr(lua_State *L, int index);
NumberOfCurrentPlayers_t *check_NumberOfCurrentPlayers_t_ptr(lua_State *L, int index);
OverlayBrowserProtocolNavigation_t *check_OverlayBrowserProtocolNavigation_t_ptr(lua_State *L, int index);
P2PSessionConnectFail_t *check_P2PSessionConnectFail_t_ptr(lua_State *L, int index);
P2PSessionRequest_t *check_P2PSessionRequest_t_ptr(lua_State *L, int index);
P2PSessionState_t *check_P2PSessionState_t_ptr(lua_State *L, int index);
PersonaStateChange_t *check_PersonaStateChange_t_ptr(lua_State *L, int index);
PlaybackStatusHasChanged_t *check_PlaybackStatusHasChanged_t_ptr(lua_State *L, int index);
RemotePlayInputKey_t *check_RemotePlayInputKey_t_ptr(lua_State *L, int index);
RemotePlayInputMouseMotion_t *check_RemotePlayInputMouseMotion_t_ptr(lua_State *L, int index);
RemotePlayInputMouseWheel_t *check_RemotePlayInputMouseWheel_t_ptr(lua_State *L, int index);
RemotePlayInput_t *check_RemotePlayInput_t_ptr(lua_State *L, int index);
RemoteStorageDeletePublishedFileResult_t *check_RemoteStorageDeletePublishedFileResult_t_ptr(lua_State *L, int index);
RemoteStorageDownloadUGCResult_t *check_RemoteStorageDownloadUGCResult_t_ptr(lua_State *L, int index);
RemoteStorageEnumeratePublishedFilesByUserActionResult_t *check_RemoteStorageEnumeratePublishedFilesByUserActionResult_t_ptr(lua_State *L, int index);
RemoteStorageEnumerateUserPublishedFilesResult_t *check_RemoteStorageEnumerateUserPublishedFilesResult_t_ptr(lua_State *L, int index);
RemoteStorageEnumerateUserSharedWorkshopFilesResult_t *check_RemoteStorageEnumerateUserSharedWorkshopFilesResult_t_ptr(lua_State *L, int index);
RemoteStorageEnumerateUserSubscribedFilesResult_t *check_RemoteStorageEnumerateUserSubscribedFilesResult_t_ptr(lua_State *L, int index);
RemoteStorageEnumerateWorkshopFilesResult_t *check_RemoteStorageEnumerateWorkshopFilesResult_t_ptr(lua_State *L, int index);
RemoteStorageFileReadAsyncComplete_t *check_RemoteStorageFileReadAsyncComplete_t_ptr(lua_State *L, int index);
RemoteStorageFileShareResult_t *check_RemoteStorageFileShareResult_t_ptr(lua_State *L, int index);
RemoteStorageFileWriteAsyncComplete_t *check_RemoteStorageFileWriteAsyncComplete_t_ptr(lua_State *L, int index);
RemoteStorageGetPublishedFileDetailsResult_t *check_RemoteStorageGetPublishedFileDetailsResult_t_ptr(lua_State *L, int index);
RemoteStorageGetPublishedItemVoteDetailsResult_t *check_RemoteStorageGetPublishedItemVoteDetailsResult_t_ptr(lua_State *L, int index);
RemoteStorageLocalFileChange_t *check_RemoteStorageLocalFileChange_t_ptr(lua_State *L, int index);
RemoteStoragePublishFileProgress_t *check_RemoteStoragePublishFileProgress_t_ptr(lua_State *L, int index);
RemoteStoragePublishFileResult_t *check_RemoteStoragePublishFileResult_t_ptr(lua_State *L, int index);
RemoteStoragePublishedFileDeleted_t *check_RemoteStoragePublishedFileDeleted_t_ptr(lua_State *L, int index);
RemoteStoragePublishedFileSubscribed_t *check_RemoteStoragePublishedFileSubscribed_t_ptr(lua_State *L, int index);
RemoteStoragePublishedFileUnsubscribed_t *check_RemoteStoragePublishedFileUnsubscribed_t_ptr(lua_State *L, int index);
RemoteStoragePublishedFileUpdated_t *check_RemoteStoragePublishedFileUpdated_t_ptr(lua_State *L, int index);
RemoteStorageSetUserPublishedFileActionResult_t *check_RemoteStorageSetUserPublishedFileActionResult_t_ptr(lua_State *L, int index);
RemoteStorageSubscribePublishedFileResult_t *check_RemoteStorageSubscribePublishedFileResult_t_ptr(lua_State *L, int index);
RemoteStorageUnsubscribePublishedFileResult_t *check_RemoteStorageUnsubscribePublishedFileResult_t_ptr(lua_State *L, int index);
RemoteStorageUpdatePublishedFileResult_t *check_RemoteStorageUpdatePublishedFileResult_t_ptr(lua_State *L, int index);
RemoteStorageUpdateUserPublishedItemVoteResult_t *check_RemoteStorageUpdateUserPublishedItemVoteResult_t_ptr(lua_State *L, int index);
RemoteStorageUserVoteDetails_t *check_RemoteStorageUserVoteDetails_t_ptr(lua_State *L, int index);
RemoveAppDependencyResult_t *check_RemoveAppDependencyResult_t_ptr(lua_State *L, int index);
RemoveUGCDependencyResult_t *check_RemoveUGCDependencyResult_t_ptr(lua_State *L, int index);
ReservationNotificationCallback_t *check_ReservationNotificationCallback_t_ptr(lua_State *L, int index);
ScreenshotReady_t *check_ScreenshotReady_t_ptr(lua_State *L, int index);
ScreenshotRequested_t *check_ScreenshotRequested_t_ptr(lua_State *L, int index);
SetUserItemVoteResult_t *check_SetUserItemVoteResult_t_ptr(lua_State *L, int index);
SocketStatusCallback_t *check_SocketStatusCallback_t_ptr(lua_State *L, int index);
StartPlaytimeTrackingResult_t *check_StartPlaytimeTrackingResult_t_ptr(lua_State *L, int index);
SteamAPICallCompleted_t *check_SteamAPICallCompleted_t_ptr(lua_State *L, int index);
SteamIPAddress_t *check_SteamIPAddress_t_ptr(lua_State *L, int index);
SteamInputActionEvent_t *check_SteamInputActionEvent_t_ptr(lua_State *L, int index);
SteamInputConfigurationLoaded_t *check_SteamInputConfigurationLoaded_t_ptr(lua_State *L, int index);
SteamInputDeviceConnected_t *check_SteamInputDeviceConnected_t_ptr(lua_State *L, int index);
SteamInputDeviceDisconnected_t *check_SteamInputDeviceDisconnected_t_ptr(lua_State *L, int index);
SteamInputGamepadSlotChange_t *check_SteamInputGamepadSlotChange_t_ptr(lua_State *L, int index);
SteamInventoryDefinitionUpdate_t *check_SteamInventoryDefinitionUpdate_t_ptr(lua_State *L, int index);
SteamInventoryEligiblePromoItemDefIDs_t *check_SteamInventoryEligiblePromoItemDefIDs_t_ptr(lua_State *L, int index);
SteamInventoryFullUpdate_t *check_SteamInventoryFullUpdate_t_ptr(lua_State *L, int index);
SteamInventoryRequestPricesResult_t *check_SteamInventoryRequestPricesResult_t_ptr(lua_State *L, int index);
SteamInventoryResultReady_t *check_SteamInventoryResultReady_t_ptr(lua_State *L, int index);
SteamInventoryStartPurchaseResult_t *check_SteamInventoryStartPurchaseResult_t_ptr(lua_State *L, int index);
SteamItemDetails_t *check_SteamItemDetails_t_ptr(lua_State *L, int index);
SteamNetAuthenticationStatus_t *check_SteamNetAuthenticationStatus_t_ptr(lua_State *L, int index);
SteamNetConnectionInfo_t *check_SteamNetConnectionInfo_t_ptr(lua_State *L, int index);
SteamNetConnectionRealTimeLaneStatus_t *check_SteamNetConnectionRealTimeLaneStatus_t_ptr(lua_State *L, int index);
SteamNetConnectionRealTimeStatus_t *check_SteamNetConnectionRealTimeStatus_t_ptr(lua_State *L, int index);
SteamNetConnectionStatusChangedCallback_t *check_SteamNetConnectionStatusChangedCallback_t_ptr(lua_State *L, int index);
SteamNetworkPingLocation_t *check_SteamNetworkPingLocation_t_ptr(lua_State *L, int index);
SteamNetworkingConfigValue_t *check_SteamNetworkingConfigValue_t_ptr(lua_State *L, int index);
SteamNetworkingFakeIPResult_t *check_SteamNetworkingFakeIPResult_t_ptr(lua_State *L, int index);
SteamNetworkingIPAddr *check_SteamNetworkingIPAddr_ptr(lua_State *L, int index);
SteamNetworkingIdentity *check_SteamNetworkingIdentity_ptr(lua_State *L, int index);
SteamNetworkingMessagesSessionFailed_t *check_SteamNetworkingMessagesSessionFailed_t_ptr(lua_State *L, int index);
SteamNetworkingMessagesSessionRequest_t *check_SteamNetworkingMessagesSessionRequest_t_ptr(lua_State *L, int index);
SteamParamStringArray_t *check_SteamParamStringArray_t_ptr(lua_State *L, int index);
SteamParentalSettingsChanged_t *check_SteamParentalSettingsChanged_t_ptr(lua_State *L, int index);
SteamPartyBeaconLocation_t *check_SteamPartyBeaconLocation_t_ptr(lua_State *L, int index);
SteamRelayNetworkStatus_t *check_SteamRelayNetworkStatus_t_ptr(lua_State *L, int index);
SteamRemotePlaySessionConnected_t *check_SteamRemotePlaySessionConnected_t_ptr(lua_State *L, int index);
SteamRemotePlaySessionDisconnected_t *check_SteamRemotePlaySessionDisconnected_t_ptr(lua_State *L, int index);
SteamRemotePlayTogetherGuestInvite_t *check_SteamRemotePlayTogetherGuestInvite_t_ptr(lua_State *L, int index);
SteamServerConnectFailure_t *check_SteamServerConnectFailure_t_ptr(lua_State *L, int index);
SteamServersConnected_t *check_SteamServersConnected_t_ptr(lua_State *L, int index);
SteamServersDisconnected_t *check_SteamServersDisconnected_t_ptr(lua_State *L, int index);
SteamShutdown_t *check_SteamShutdown_t_ptr(lua_State *L, int index);
SteamTimelineEventRecordingExists_t *check_SteamTimelineEventRecordingExists_t_ptr(lua_State *L, int index);
SteamTimelineGamePhaseRecordingExists_t *check_SteamTimelineGamePhaseRecordingExists_t_ptr(lua_State *L, int index);
SteamUGCDetails_t *check_SteamUGCDetails_t_ptr(lua_State *L, int index);
SteamUGCQueryCompleted_t *check_SteamUGCQueryCompleted_t_ptr(lua_State *L, int index);
SteamUGCRequestUGCDetailsResult_t *check_SteamUGCRequestUGCDetailsResult_t_ptr(lua_State *L, int index);
StopPlaytimeTrackingResult_t *check_StopPlaytimeTrackingResult_t_ptr(lua_State *L, int index);
StoreAuthURLResponse_t *check_StoreAuthURLResponse_t_ptr(lua_State *L, int index);
SubmitItemUpdateResult_t *check_SubmitItemUpdateResult_t_ptr(lua_State *L, int index);
TimedTrialStatus_t *check_TimedTrialStatus_t_ptr(lua_State *L, int index);
UnreadChatMessagesChanged_t *check_UnreadChatMessagesChanged_t_ptr(lua_State *L, int index);
UserAchievementIconFetched_t *check_UserAchievementIconFetched_t_ptr(lua_State *L, int index);
UserAchievementStored_t *check_UserAchievementStored_t_ptr(lua_State *L, int index);
UserFavoriteItemsListChanged_t *check_UserFavoriteItemsListChanged_t_ptr(lua_State *L, int index);
UserStatsReceived_t *check_UserStatsReceived_t_ptr(lua_State *L, int index);
UserStatsStored_t *check_UserStatsStored_t_ptr(lua_State *L, int index);
UserStatsUnloaded_t *check_UserStatsUnloaded_t_ptr(lua_State *L, int index);
UserSubscribedItemsListChanged_t *check_UserSubscribedItemsListChanged_t_ptr(lua_State *L, int index);
ValidateAuthTicketResponse_t *check_ValidateAuthTicketResponse_t_ptr(lua_State *L, int index);
VolumeHasChanged_t *check_VolumeHasChanged_t_ptr(lua_State *L, int index);
WorkshopEULAStatus_t *check_WorkshopEULAStatus_t_ptr(lua_State *L, int index);
gameserveritem_t *check_gameserveritem_t_ptr(lua_State *L, int index);
servernetadr_t *check_servernetadr_t_ptr(lua_State *L, int index);
void register_Client_auto(lua_State *L, bool is_gs);
void add_Client_auto(lua_State *L);
void init_Client_auto(lua_State *L);
void shutdown_Client_auto(lua_State *L);
extern int Client_ref;
void register_User_auto(lua_State *L);
void add_User_auto(lua_State *L);
void init_User_auto(lua_State *L);
void shutdown_User_auto(lua_State *L);
extern int User_ref;
void register_Friends_auto(lua_State *L);
void add_Friends_auto(lua_State *L);
void init_Friends_auto(lua_State *L);
void shutdown_Friends_auto(lua_State *L);
extern int Friends_ref;
void register_Utils_auto(lua_State *L, bool is_gs);
void add_Utils_auto(lua_State *L);
void init_Utils_auto(lua_State *L);
void shutdown_Utils_auto(lua_State *L);
extern int Utils_ref;
void register_Matchmaking_auto(lua_State *L);
void add_Matchmaking_auto(lua_State *L);
void init_Matchmaking_auto(lua_State *L);
void shutdown_Matchmaking_auto(lua_State *L);
extern int Matchmaking_ref;
void register_MatchmakingServers_auto(lua_State *L);
void add_MatchmakingServers_auto(lua_State *L);
void init_MatchmakingServers_auto(lua_State *L);
void shutdown_MatchmakingServers_auto(lua_State *L);
extern int MatchmakingServers_ref;
void register_Parties_auto(lua_State *L);
void add_Parties_auto(lua_State *L);
void init_Parties_auto(lua_State *L);
void shutdown_Parties_auto(lua_State *L);
extern int Parties_ref;
void register_RemoteStorage_auto(lua_State *L);
void add_RemoteStorage_auto(lua_State *L);
void init_RemoteStorage_auto(lua_State *L);
void shutdown_RemoteStorage_auto(lua_State *L);
extern int RemoteStorage_ref;
void register_UserStats_auto(lua_State *L);
void add_UserStats_auto(lua_State *L);
void init_UserStats_auto(lua_State *L);
void shutdown_UserStats_auto(lua_State *L);
extern int UserStats_ref;
void register_Apps_auto(lua_State *L);
void add_Apps_auto(lua_State *L);
void init_Apps_auto(lua_State *L);
void shutdown_Apps_auto(lua_State *L);
extern int Apps_ref;
void register_Networking_auto(lua_State *L, bool is_gs);
void add_Networking_auto(lua_State *L);
void init_Networking_auto(lua_State *L);
void shutdown_Networking_auto(lua_State *L);
extern int Networking_ref;
void register_Screenshots_auto(lua_State *L);
void add_Screenshots_auto(lua_State *L);
void init_Screenshots_auto(lua_State *L);
void shutdown_Screenshots_auto(lua_State *L);
extern int Screenshots_ref;
void register_Music_auto(lua_State *L);
void add_Music_auto(lua_State *L);
void init_Music_auto(lua_State *L);
void shutdown_Music_auto(lua_State *L);
extern int Music_ref;
void register_HTTP_auto(lua_State *L, bool is_gs);
void add_HTTP_auto(lua_State *L);
void init_HTTP_auto(lua_State *L);
void shutdown_HTTP_auto(lua_State *L);
extern int HTTP_ref;
void register_Input_auto(lua_State *L);
void add_Input_auto(lua_State *L);
void init_Input_auto(lua_State *L);
void shutdown_Input_auto(lua_State *L);
extern int Input_ref;
void register_Controller_auto(lua_State *L);
void add_Controller_auto(lua_State *L);
void init_Controller_auto(lua_State *L);
void shutdown_Controller_auto(lua_State *L);
extern int Controller_ref;
void register_UGC_auto(lua_State *L, bool is_gs);
void add_UGC_auto(lua_State *L);
void init_UGC_auto(lua_State *L);
void shutdown_UGC_auto(lua_State *L);
extern int UGC_ref;
void register_HTMLSurface_auto(lua_State *L);
void add_HTMLSurface_auto(lua_State *L);
void init_HTMLSurface_auto(lua_State *L);
void shutdown_HTMLSurface_auto(lua_State *L);
extern int HTMLSurface_ref;
void register_Inventory_auto(lua_State *L, bool is_gs);
void add_Inventory_auto(lua_State *L);
void init_Inventory_auto(lua_State *L);
void shutdown_Inventory_auto(lua_State *L);
extern int Inventory_ref;
void register_Timeline_auto(lua_State *L);
void add_Timeline_auto(lua_State *L);
void init_Timeline_auto(lua_State *L);
void shutdown_Timeline_auto(lua_State *L);
extern int Timeline_ref;
void register_Video_auto(lua_State *L);
void add_Video_auto(lua_State *L);
void init_Video_auto(lua_State *L);
void shutdown_Video_auto(lua_State *L);
extern int Video_ref;
void register_ParentalSettings_auto(lua_State *L);
void add_ParentalSettings_auto(lua_State *L);
void init_ParentalSettings_auto(lua_State *L);
void shutdown_ParentalSettings_auto(lua_State *L);
extern int ParentalSettings_ref;
void register_RemotePlay_auto(lua_State *L);
void add_RemotePlay_auto(lua_State *L);
void init_RemotePlay_auto(lua_State *L);
void shutdown_RemotePlay_auto(lua_State *L);
extern int RemotePlay_ref;
void register_NetworkingMessages_auto(lua_State *L, bool is_gs);
void add_NetworkingMessages_auto(lua_State *L);
void init_NetworkingMessages_auto(lua_State *L);
void shutdown_NetworkingMessages_auto(lua_State *L);
extern int NetworkingMessages_ref;
void register_NetworkingSockets_auto(lua_State *L, bool is_gs);
void add_NetworkingSockets_auto(lua_State *L);
void init_NetworkingSockets_auto(lua_State *L);
void shutdown_NetworkingSockets_auto(lua_State *L);
extern int NetworkingSockets_ref;
void register_NetworkingUtils_auto(lua_State *L);
void add_NetworkingUtils_auto(lua_State *L);
void init_NetworkingUtils_auto(lua_State *L);
void shutdown_NetworkingUtils_auto(lua_State *L);
extern int NetworkingUtils_ref;
void register_GameServer_auto(lua_State *L);
void add_GameServer_auto(lua_State *L);
void init_GameServer_auto(lua_State *L);
void shutdown_GameServer_auto(lua_State *L);
extern int GameServer_ref;
void register_GameServerStats_auto(lua_State *L);
void add_GameServerStats_auto(lua_State *L);
void init_GameServerStats_auto(lua_State *L);
void shutdown_GameServerStats_auto(lua_State *L);
extern int GameServerStats_ref;
void add_GameServerClient_auto(lua_State *L);
void init_GameServerClient_auto(lua_State *L);
void shutdown_GameServerClient_auto(lua_State *L);
extern int GameServerClient_ref;
void add_GameServerUtils_auto(lua_State *L);
void init_GameServerUtils_auto(lua_State *L);
void shutdown_GameServerUtils_auto(lua_State *L);
extern int GameServerUtils_ref;
void add_GameServerNetworking_auto(lua_State *L);
void init_GameServerNetworking_auto(lua_State *L);
void shutdown_GameServerNetworking_auto(lua_State *L);
extern int GameServerNetworking_ref;
void add_GameServerHTTP_auto(lua_State *L);
void init_GameServerHTTP_auto(lua_State *L);
void shutdown_GameServerHTTP_auto(lua_State *L);
extern int GameServerHTTP_ref;
void add_GameServerUGC_auto(lua_State *L);
void init_GameServerUGC_auto(lua_State *L);
void shutdown_GameServerUGC_auto(lua_State *L);
extern int GameServerUGC_ref;
void add_GameServerInventory_auto(lua_State *L);
void init_GameServerInventory_auto(lua_State *L);
void shutdown_GameServerInventory_auto(lua_State *L);
extern int GameServerInventory_ref;
void add_GameServerNetworkingMessages_auto(lua_State *L);
void init_GameServerNetworkingMessages_auto(lua_State *L);
void shutdown_GameServerNetworkingMessages_auto(lua_State *L);
extern int GameServerNetworkingMessages_ref;
void add_GameServerNetworkingSockets_auto(lua_State *L);
void init_GameServerNetworkingSockets_auto(lua_State *L);
void shutdown_GameServerNetworkingSockets_auto(lua_State *L);
extern int GameServerNetworkingSockets_ref;

} // namespace luasteam

#endif // LUASTEAM_AUTO_HPP
