#include "auto.hpp"

namespace luasteam {

void add_consts_auto(lua_State *L) {
	lua_pushinteger(L, 0x0);
	lua_setfield(L, -2, "k_uAppIdInvalid");
	lua_pushinteger(L, 0x0);
	lua_setfield(L, -2, "k_uDepotIdInvalid");
	luasteam::pushuint64(L, 0x0);
	lua_setfield(L, -2, "k_uAPICallInvalid");
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "k_uAccountIdInvalid");
	luasteam::pushuint64(L, 0);
	lua_setfield(L, -2, "k_ulPartyBeaconIdInvalid");
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "k_HAuthTicketInvalid");
	lua_pushinteger(L, 0xFFFFFFFF);
	lua_setfield(L, -2, "k_unSteamAccountIDMask");
	lua_pushinteger(L, 0x000FFFFF);
	lua_setfield(L, -2, "k_unSteamAccountInstanceMask");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "k_unSteamUserDefaultInstance");
	lua_pushinteger(L, 64);
	lua_setfield(L, -2, "k_cchGameExtraInfoMax");
	lua_pushinteger(L, 1024);
	lua_setfield(L, -2, "k_cchMaxSteamErrMsg");
	lua_pushinteger(L, 64);
	lua_setfield(L, -2, "k_cchMaxFriendsGroupName");
	lua_pushinteger(L, 100);
	lua_setfield(L, -2, "k_cFriendsGroupLimit");
	lua_pushinteger(L, - 1);
	lua_setfield(L, -2, "k_FriendsGroupID_Invalid");
	lua_pushinteger(L, 50);
	lua_setfield(L, -2, "k_cEnumerateFollowersMax");
	lua_pushinteger(L, 0xFFFF);
	lua_setfield(L, -2, "k_usFriendGameInfoQueryPort_NotInitialized");
	lua_pushinteger(L, 0xFFFE);
	lua_setfield(L, -2, "k_usFriendGameInfoQueryPort_Error");
	lua_pushinteger(L, 8192);
	lua_setfield(L, -2, "k_cubChatMetadataMax");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "k_cbMaxGameServerGameDir");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "k_cbMaxGameServerMapName");
	lua_pushinteger(L, 64);
	lua_setfield(L, -2, "k_cbMaxGameServerGameDescription");
	lua_pushinteger(L, 64);
	lua_setfield(L, -2, "k_cbMaxGameServerName");
	lua_pushinteger(L, 128);
	lua_setfield(L, -2, "k_cbMaxGameServerTags");
	lua_pushinteger(L, 2048);
	lua_setfield(L, -2, "k_cbMaxGameServerGameData");
	lua_pushinteger(L, 0xffffffff);
	lua_setfield(L, -2, "HSERVERQUERY_INVALID");
	lua_pushinteger(L, 0x00);
	lua_setfield(L, -2, "k_unFavoriteFlagNone");
	lua_pushinteger(L, 0x01);
	lua_setfield(L, -2, "k_unFavoriteFlagFavorite");
	lua_pushinteger(L, 0x02);
	lua_setfield(L, -2, "k_unFavoriteFlagHistory");
	lua_pushinteger(L, 100 * 1024 * 1024);
	lua_setfield(L, -2, "k_unMaxCloudFileChunkSize");
	luasteam::pushuint64(L, 0);
	lua_setfield(L, -2, "k_PublishedFileIdInvalid");
	luasteam::pushuint64(L, 0xffffffffffffffffull);
	lua_setfield(L, -2, "k_UGCHandleInvalid");
	luasteam::pushuint64(L, 0xffffffffffffffffull);
	lua_setfield(L, -2, "k_PublishedFileUpdateHandleInvalid");
	luasteam::pushuint64(L, 0xffffffffffffffffull);
	lua_setfield(L, -2, "k_UGCFileStreamHandleInvalid");
	lua_pushinteger(L, 128 + 1);
	lua_setfield(L, -2, "k_cchPublishedDocumentTitleMax");
	lua_pushinteger(L, 8000);
	lua_setfield(L, -2, "k_cchPublishedDocumentDescriptionMax");
	lua_pushinteger(L, 8000);
	lua_setfield(L, -2, "k_cchPublishedDocumentChangeDescriptionMax");
	lua_pushinteger(L, 50);
	lua_setfield(L, -2, "k_unEnumeratePublishedFilesMaxResults");
	lua_pushinteger(L, 1024 + 1);
	lua_setfield(L, -2, "k_cchTagListMax");
	lua_pushinteger(L, 260);
	lua_setfield(L, -2, "k_cchFilenameMax");
	lua_pushinteger(L, 256);
	lua_setfield(L, -2, "k_cchPublishedFileURLMax");
	lua_pushinteger(L, 240);
	lua_setfield(L, -2, "k_cubAppProofOfPurchaseKeyMax");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "k_nScreenshotMaxTaggedUsers");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "k_nScreenshotMaxTaggedPublishedFiles");
	lua_pushinteger(L, 255);
	lua_setfield(L, -2, "k_cubUFSTagTypeMax");
	lua_pushinteger(L, 255);
	lua_setfield(L, -2, "k_cubUFSTagValueMax");
	lua_pushinteger(L, 200);
	lua_setfield(L, -2, "k_ScreenshotThumbWidth");
	luasteam::pushuint64(L, 0xffffffffffffffffull);
	lua_setfield(L, -2, "k_UGCQueryHandleInvalid");
	luasteam::pushuint64(L, 0xffffffffffffffffull);
	lua_setfield(L, -2, "k_UGCUpdateHandleInvalid");
	lua_pushinteger(L, 50);
	lua_setfield(L, -2, "kNumUGCResultsPerPage");
	lua_pushinteger(L, 5000);
	lua_setfield(L, -2, "k_cchDeveloperMetadataMax");
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "INVALID_HTMLBROWSER");
	luasteam::pushuint64(L, ( SteamItemInstanceID_t ) ~ 0);
	lua_setfield(L, -2, "k_SteamItemInstanceIDInvalid");
	lua_pushinteger(L, - 1);
	lua_setfield(L, -2, "k_SteamInventoryResultInvalid");
	luasteam::pushuint64(L, 0xffffffffffffffffull);
	lua_setfield(L, -2, "k_SteamInventoryUpdateHandleInvalid");
	lua_pushinteger(L, 1000);
	lua_setfield(L, -2, "k_unMaxTimelinePriority");
	lua_pushinteger(L, 1000000);
	lua_setfield(L, -2, "k_unTimelinePriority_KeepCurrentValue");
	lua_pushnumber(L, 600.f);
	lua_setfield(L, -2, "k_flMaxTimelineEventDuration");
	lua_pushinteger(L, 64);
	lua_setfield(L, -2, "k_cchMaxPhaseIDLength");
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "k_HSteamNetConnection_Invalid");
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "k_HSteamListenSocket_Invalid");
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "k_HSteamNetPollGroup_Invalid");
	lua_pushinteger(L, 1024);
	lua_setfield(L, -2, "k_cchMaxSteamNetworkingErrMsg");
	lua_pushinteger(L, 128);
	lua_setfield(L, -2, "k_cchSteamNetworkingMaxConnectionCloseReason");
	lua_pushinteger(L, 128);
	lua_setfield(L, -2, "k_cchSteamNetworkingMaxConnectionDescription");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "k_cchSteamNetworkingMaxConnectionAppName");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "k_nSteamNetworkConnectionInfoFlags_Unauthenticated");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "k_nSteamNetworkConnectionInfoFlags_Unencrypted");
	lua_pushinteger(L, 4);
	lua_setfield(L, -2, "k_nSteamNetworkConnectionInfoFlags_LoopbackBuffers");
	lua_pushinteger(L, 8);
	lua_setfield(L, -2, "k_nSteamNetworkConnectionInfoFlags_Fast");
	lua_pushinteger(L, 16);
	lua_setfield(L, -2, "k_nSteamNetworkConnectionInfoFlags_Relayed");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "k_nSteamNetworkConnectionInfoFlags_DualWifi");
	lua_pushinteger(L, 512 * 1024);
	lua_setfield(L, -2, "k_cbMaxSteamNetworkingSocketsMessageSizeSend");
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "k_nSteamNetworkingSend_Unreliable");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "k_nSteamNetworkingSend_NoNagle");
	lua_pushinteger(L, k_nSteamNetworkingSend_Unreliable | k_nSteamNetworkingSend_NoNagle);
	lua_setfield(L, -2, "k_nSteamNetworkingSend_UnreliableNoNagle");
	lua_pushinteger(L, 4);
	lua_setfield(L, -2, "k_nSteamNetworkingSend_NoDelay");
	lua_pushinteger(L, k_nSteamNetworkingSend_Unreliable | k_nSteamNetworkingSend_NoDelay | k_nSteamNetworkingSend_NoNagle);
	lua_setfield(L, -2, "k_nSteamNetworkingSend_UnreliableNoDelay");
	lua_pushinteger(L, 8);
	lua_setfield(L, -2, "k_nSteamNetworkingSend_Reliable");
	lua_pushinteger(L, k_nSteamNetworkingSend_Reliable | k_nSteamNetworkingSend_NoNagle);
	lua_setfield(L, -2, "k_nSteamNetworkingSend_ReliableNoNagle");
	lua_pushinteger(L, 16);
	lua_setfield(L, -2, "k_nSteamNetworkingSend_UseCurrentThread");
	lua_pushinteger(L, 32);
	lua_setfield(L, -2, "k_nSteamNetworkingSend_AutoRestartBrokenSession");
	lua_pushinteger(L, 1024);
	lua_setfield(L, -2, "k_cchMaxSteamNetworkingPingLocationString");
	lua_pushinteger(L, - 1);
	lua_setfield(L, -2, "k_nSteamNetworkingPing_Failed");
	lua_pushinteger(L, - 2);
	lua_setfield(L, -2, "k_nSteamNetworkingPing_Unknown");
	lua_pushinteger(L, - 1);
	lua_setfield(L, -2, "k_nSteamNetworkingConfig_P2P_Transport_ICE_Enable_Default");
	lua_pushinteger(L, 0);
	lua_setfield(L, -2, "k_nSteamNetworkingConfig_P2P_Transport_ICE_Enable_Disable");
	lua_pushinteger(L, 1);
	lua_setfield(L, -2, "k_nSteamNetworkingConfig_P2P_Transport_ICE_Enable_Relay");
	lua_pushinteger(L, 2);
	lua_setfield(L, -2, "k_nSteamNetworkingConfig_P2P_Transport_ICE_Enable_Private");
	lua_pushinteger(L, 4);
	lua_setfield(L, -2, "k_nSteamNetworkingConfig_P2P_Transport_ICE_Enable_Public");
	lua_pushinteger(L, 0x7fffffff);
	lua_setfield(L, -2, "k_nSteamNetworkingConfig_P2P_Transport_ICE_Enable_All");
	lua_pushinteger(L, ( ( uint32 ) 'd' << 16U ) | ( ( uint32 ) 'e' << 8U ) | ( uint32 ) 'v');
	lua_setfield(L, -2, "k_SteamDatagramPOPID_dev");
	lua_pushinteger(L, 0xffff);
	lua_setfield(L, -2, "STEAMGAMESERVER_QUERY_PORT_SHARED");
	lua_pushinteger(L, STEAMGAMESERVER_QUERY_PORT_SHARED);
	lua_setfield(L, -2, "MASTERSERVERUPDATERPORT_USEGAMESOCKETSHARE");
	lua_pushinteger(L, 512);
	lua_setfield(L, -2, "k_cbSteamDatagramMaxSerializedTicket");
	lua_pushinteger(L, 2048);
	lua_setfield(L, -2, "k_cbMaxSteamDatagramGameCoordinatorServerLoginAppData");
	lua_pushinteger(L, 4096);
	lua_setfield(L, -2, "k_cbMaxSteamDatagramGameCoordinatorServerLoginSerialized");
	lua_pushinteger(L, 1200);
	lua_setfield(L, -2, "k_cbSteamNetworkingSocketsFakeUDPPortRecommendedMTU");
	lua_pushinteger(L, 4096);
	lua_setfield(L, -2, "k_cbSteamNetworkingSocketsFakeUDPPortMaxMessageSize");
	luasteam::pushuint64(L, UINT64_MAX);
	lua_setfield(L, -2, "STEAM_INPUT_HANDLE_ALL_CONTROLLERS");
	lua_pushinteger(L, 16);
	lua_setfield(L, -2, "STEAM_INPUT_MAX_ANALOG_ACTIONS");
	lua_pushnumber(L, 1.0f);
	lua_setfield(L, -2, "STEAM_INPUT_MAX_ANALOG_ACTION_DATA");
	lua_pushinteger(L, 16);
	lua_setfield(L, -2, "STEAM_INPUT_MAX_COUNT");
	lua_pushinteger(L, 16);
	lua_setfield(L, -2, "STEAM_INPUT_MAX_ACTIVE_LAYERS");
	lua_pushinteger(L, 128);
	lua_setfield(L, -2, "STEAM_INPUT_MAX_DIGITAL_ACTIONS");
	lua_pushinteger(L, 8);
	lua_setfield(L, -2, "STEAM_INPUT_MAX_ORIGINS");
	lua_pushnumber(L, -8);
	lua_setfield(L, -2, "STEAM_INPUT_MIN_ANALOG_ACTION_DATA");
}

} // namespace luasteam
